<?php
/**
 * PSOBB Website: Bounty Board & Community Missions
 * 
 * Renders the active Hunter's Guild personal bounties and the server-wide 
 * community events. Interacts with `redeem_bounty.php` and `abandon_bounty.php`
 * securely using CSRF-protected AJAX calls.
 */
require_once __DIR__ . '/api/config.php';
require_once __DIR__ . '/api/functions.php';
start_secure_session();

// Global page variables mapped before headers
$page_title = 'Hunters Guild - Bounty Board';
$current_page = 'missions';
include 'includes/header.php';
require_once 'api/db.php';

$db = get_db();

// -------------------------------------------------------------------------
// 0. Fetch Pending Redemptions
// Fetches completed missions that have not yet had their rewards disbursed in-game.
// -------------------------------------------------------------------------
$pending_redemptions = [];
$account_id = $_SESSION['user']['account_id'] ?? 0;
if ($account_id) {
    $pr_res = $db->prepare("SELECT pm.id as pm_id, m.title, m.description, m.goal_type, m.goal_target, m.reward_item_string 
                            FROM player_missions pm 
                            JOIN missions m ON pm.mission_id = m.id 
                            WHERE pm.account_id = :accId AND pm.status = 'ready_to_redeem' 
                            ORDER BY pm.id DESC");
    $pr_res->bindValue(':accId', $account_id, SQLITE3_INTEGER);
    $pr_exec = $pr_res->execute();
    while ($row = $pr_exec->fetchArray(SQLITE3_ASSOC)) {
        $pending_redemptions[] = $row;
    }
}

// -------------------------------------------------------------------------
// 1. Fetch Global Top 10 Leaderboard
// Ranks players on the frontend based on the total aggregate of all completed bounties.
// -------------------------------------------------------------------------
$leaderboard = [];
$lb_res = $db->query("SELECT u.username, COUNT(pm.id) as completions 
                      FROM player_missions pm 
                      JOIN users u ON pm.account_id = u.account_id 
                      WHERE pm.status = 'completed' 
                      GROUP BY u.username 
                      ORDER BY completions DESC 
                      LIMIT 10");
while ($row = $lb_res->fetchArray(SQLITE3_ASSOC)) {
    $leaderboard[] = $row;
}

// -------------------------------------------------------------------------
// 2. Fetch Global Active Bounties Feed
// Populates the live feed of in-progress bounties dynamically generated by Gemini.
// -------------------------------------------------------------------------
$active_bounties = [];
$ab_query = "SELECT pm.id as pm_id, u.username, m.title, m.description, m.goal_type, m.goal_target, m.reward_item_string 
             FROM player_missions pm 
             JOIN missions m ON pm.mission_id = m.id 
             JOIN users u ON pm.account_id = u.account_id 
             WHERE pm.status = 'in_progress' ";

if ($account_id) {
    // SQLite boolean expression: (u.account_id = X) evaluates to 1 or 0. Sorting DESC puts 1s at the top!
    $ab_query .= "ORDER BY (u.account_id = :accId) DESC, pm.id DESC";
    $ab_stmt = $db->prepare($ab_query);
    $ab_stmt->bindValue(':accId', $account_id, SQLITE3_INTEGER);
    $ab_res = $ab_stmt->execute();
} else {
    $ab_query .= "ORDER BY pm.id DESC";
    $ab_res = $db->query($ab_query);
}
while ($row = $ab_res->fetchArray(SQLITE3_ASSOC)) {
    $active_bounties[] = $row;
}

// -------------------------------------------------------------------------
// 3. Fetch Community Events (Active and Claimable)
// -------------------------------------------------------------------------
$active_community_events = [];
$claimable_community_events = [];

// Get active events
$ce_res = $db->query("SELECT id, title, description, goal_type, goal_target, target_amount, current_progress, reward_item_string, top_3_reward_item_string
                      FROM community_events 
                      WHERE status = 'active'
                      ORDER BY id DESC");
$top_contributors = [];
while ($row = $ce_res->fetchArray(SQLITE3_ASSOC)) {
    $active_community_events[] = $row;
    
    // Fetch Top 3
    $top_stmt = $db->prepare("SELECT u.username, cep.contribution_count FROM community_event_participants cep JOIN users u ON cep.account_id = u.account_id WHERE cep.event_id = :eid ORDER BY cep.contribution_count DESC LIMIT 3");
    $top_stmt->bindValue(':eid', $row['id'], SQLITE3_INTEGER);
    $top_exec = $top_stmt->execute();
    while ($t_row = $top_exec->fetchArray(SQLITE3_ASSOC)) {
        $top_contributors[$row['id']][] = $t_row;
    }
}

// Get claimable events for the current user
if ($account_id) {
    $cc_res = $db->prepare("SELECT ce.id as event_id, ce.title, ce.description, ce.reward_item_string, ce.top_3_reward_item_string, cep.contribution_count
                            FROM community_events ce
                            JOIN community_event_participants cep ON ce.id = cep.event_id
                            WHERE ce.status = 'completed' AND cep.account_id = :accId AND cep.reward_claimed = 0");
    $cc_res->bindValue(':accId', $account_id, SQLITE3_INTEGER);
    $cc_exec = $cc_res->execute();
    while ($row = $cc_exec->fetchArray(SQLITE3_ASSOC)) {
        $top3_stmt = $db->prepare("SELECT account_id FROM community_event_participants WHERE event_id = :eid ORDER BY contribution_count DESC LIMIT 3");
        $top3_stmt->bindValue(':eid', $row['event_id'], SQLITE3_INTEGER);
        $top3_res = $top3_stmt->execute();
        $is_top_3 = false;
        while ($t3 = $top3_res->fetchArray(SQLITE3_ASSOC)) {
            if ($t3['account_id'] == $account_id) {
                $is_top_3 = true;
                break;
            }
        }
        $row['is_top_3'] = $is_top_3;
        $claimable_community_events[] = $row;
    }
}

?>

<link rel="stylesheet" href="css/missions.css">

<main class="container missions-wide">
    <section class="missions-hero animate-fade-in">
        <h1><?= __('Hunters Guild Active Roster') ?></h1>
        <p><?= __('The official Pioneer 2 Bounty Board. Complete unique, specially curated quests to earn meseta, rare items, and global recognition.') ?></p>
    </section>

    <div class="missions-container">
        
        <!-- Left Column: Bounties -->
        <div>
            <!-- Pending Redemptions -->
            <?php if (!empty($pending_redemptions)): ?>
                <div class="section-header delay-1" style="margin-bottom: 1rem;">
                    <h2 style="color: #00ff88;"><?= __('🎁 Ready to Redeem') ?></h2>
                </div>
                <!-- Add alert box for redemption status -->
                <div id="redeem-status" class="alert-box success" style="display: none; margin-bottom: 2rem;"></div>
                <div class="bounty-grid delay-1" style="margin-bottom: 3rem;">
                    <?php foreach ($pending_redemptions as $r): ?>
                        <div class="bounty-card" style="border-color: #00ff88; box-shadow: 0 0 15px rgba(0,255,136,0.2);">
                            <div class="bounty-header">
                                <span class="bounty-player"><?= __('Mission Complete!') ?></span>
                                <span class="bounty-status" style="background: rgba(0,255,136,0.2); color: #00ff88; border: 1px solid #00ff88;"><?= __('Awaiting Claim') ?></span>
                            </div>
                            <h3 class="bounty-title" style="color: #00ff88;"><?= htmlspecialchars($r['title']) ?></h3>
                            <p class="bounty-desc"><?= htmlspecialchars($r['description']) ?></p>
                            <div class="bounty-meta">
                                <div class="bounty-meta-row">
                                    <span class="bounty-meta-label"><?= __('Reward') ?></span>
                                    <span class="bounty-meta-val bounty-reward" style="color: #00ff88;"><?= renderRewardString($r['reward_item_string']) ?></span>
                                </div>
                            </div>
                            <button onclick="redeemBounty(<?= $r['pm_id'] ?>, this)" class="dl-btn" style="width: 100%; margin-top: 1rem; background: rgba(0, 255, 136, 0.15); border-color: #00ff88; color: #00ff88; font-weight: bold; padding: 10px;"><?= __('Claim Reward') ?></button>
                        </div>
                    <?php endforeach; ?>
                </div>
                
                <!-- Claimable Community Events -->
                <div class="bounty-grid delay-1" style="margin-bottom: 3rem;">
                    <?php foreach ($claimable_community_events as $ce): ?>
                        <div class="bounty-card" style="border-color: #ffaa00; box-shadow: 0 0 15px rgba(255,170,0,0.2);">
                            <div class="bounty-header">
                                <span class="bounty-player" style="color:#ffaa00;"><?= __('Server Event Completed!') ?></span>
                                <span class="bounty-status" style="background: rgba(255,170,0,0.2); color: #ffaa00; border: 1px solid #ffaa00;"><?= __('Awaiting Claim') ?></span>
                            </div>
                            <h3 class="bounty-title" style="color: #ffaa00;"><?= htmlspecialchars($ce['title']) ?></h3>
                            <p class="bounty-desc"><?= htmlspecialchars($ce['description']) ?></p>
                            <div class="bounty-meta">
                                <div class="bounty-meta-row">
                                    <span class="bounty-meta-label"><?= __('Your Contribution') ?></span>
                                    <span class="bounty-meta-val" style="color: #ffaa00;"><?= number_format($ce['contribution_count']) ?> <?= __('points') ?></span>
                                </div>
                                <div class="bounty-meta-row">
                                    <span class="bounty-meta-label"><?= __('Reward') ?></span>
                                    <span class="bounty-meta-val bounty-reward" style="color: #ffaa00;"><?= renderRewardString($ce['reward_item_string']) ?></span>
                                </div>
                                <?php 
                                    if ($ce['is_top_3'] && !empty($ce['top_3_reward_item_string'])) {
                                        $choices = array_map('trim', explode('|', $ce['top_3_reward_item_string']));
                                        if (count($choices) > 1): 
                                ?>
                                            <div class="bounty-meta-row" style="margin-top: 15px; border-top: 1px solid rgba(0,255,204,0.3); padding-top: 10px;">
                                                <span class="bounty-meta-label" style="color:#00ffcc; font-weight:bold;"><?= __('Top 3 Bonus Selection') ?></span>
                                                <select id="ce_bonus_choice_<?= $ce['event_id'] ?>" style="width:100%; margin-top:5px; padding:8px; background:rgba(0,0,0,0.6); border:1px solid #00ffcc; color:#00ffcc; border-radius:4px;">
                                                    <option value="">-- <?= __('Select Your Bonus Reward') ?> --</option>
                                                    <?php foreach($choices as $c): ?>
                                                        <option value="<?= htmlspecialchars($c) ?>"><?= htmlspecialchars($c) ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                        <?php else: ?>
                                            <div class="bounty-meta-row" style="margin-top: 5px;">
                                                <span class="bounty-meta-label" style="color:#00ffcc;"><?= __('Top 3 Bonus') ?></span>
                                                <span class="bounty-meta-val bounty-reward" style="color: #00ffcc;"><?= renderRewardString($ce['top_3_reward_item_string']) ?></span>
                                            </div>
                                <?php 
                                        endif; 
                                    } 
                                ?>
                            </div>
                            <button onclick="redeemCommunityEvent(<?= $ce['event_id'] ?>, this)" class="dl-btn" style="width: 100%; margin-top: 1rem; background: rgba(255,170,0,0.15); border-color: #ffaa00; color: #ffaa00; font-weight: bold; padding: 10px;"><?= __('Claim Community Reward') ?></button>
                        </div>
                    <?php endforeach; ?>
                </div>

            <?php endif; ?>
            <script>
            async function redeemBounty(pmId, btnEl) {
                btnEl.disabled = true;
                btnEl.textContent = '<?= __('Preparing...') ?>';

                const overlay = document.getElementById('drop-animation-overlay');
                const box = document.getElementById('drop-item-box');
                const thankYouText = document.getElementById('thank-you-text');
                const countdownEl = document.getElementById('countdown-text');
                const statusEl = document.getElementById('redeem-status');
                statusEl.style.display = 'none';

                // Always use default red box for rare bounty rewards
                box.className = 'drop-item-box'; 

                thankYouText.style.animation = 'none';
                thankYouText.style.opacity = '0';

                const newBox = box.cloneNode(true);
                box.parentNode.replaceChild(newBox, box);

                overlay.style.display = 'flex';

                let count = 3;
                countdownEl.textContent = count;
                countdownEl.style.display = 'block';

                const countdownInterval = setInterval(async () => {
                    count--;
                    if (count > 0) {
                        countdownEl.textContent = count;
                        countdownEl.style.transform = 'scale(1.5)';
                        setTimeout(() => countdownEl.style.transform = 'scale(1)', 100);
                    } else if (count === 0) {
                        countdownEl.style.transform = 'scale(1.5)';
                        countdownEl.textContent = "<?= __('DROPPING!') ?>";
                        
                        try {
                            const response = await fetch('/api/redeem_bounty.php', {
                                method: 'POST',
                                credentials: 'same-origin',
                                headers: { 
                                    'Content-Type': 'application/json',
                                    'X-CSRF-Token': window.getCSRFToken()
                                },
                                body: JSON.stringify({ player_mission_id: pmId })
                            });
                            const data = await response.json();
                            if (response.ok && data.success) {
                                countdownEl.style.display = 'none';
                                thankYouText.textContent = "<?= __('BOUNTY CLAIMED!') ?>";
                                thankYouText.style.animation = 'textDrop 1.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards';

                                createFireworks();

                                setTimeout(() => {
                                    overlay.style.display = 'none';
                                    statusEl.textContent = data.message;
                                    statusEl.style.display = 'block';
                                    statusEl.className = 'alert-box success';
                                    statusEl.style.color = '#1eff64';
                                    statusEl.style.borderColor = '#1eff64';
                                    btnEl.textContent = '<?= __('Claimed!') ?>';
                                    btnEl.style.background = 'rgba(255,255,255,0.1)';
                                    btnEl.style.borderColor = 'rgba(255,255,255,0.2)';
                                    btnEl.style.color = 'rgba(255,255,255,0.5)';
                                    setTimeout(() => { window.location.reload(); }, 2000);
                                }, 4000);
                            } else {
                                throw new Error(data.error || 'Failed to claim reward.');
                            }
                        } catch(e) {
                            clearInterval(countdownInterval);
                            overlay.style.display = 'none';
                            statusEl.textContent = '<?= __('Connection error: ') ?>' + e.message;
                            statusEl.style.display = 'block';
                            statusEl.className = 'alert-box';
                            statusEl.style.color = '#ff4444';
                            statusEl.style.borderColor = '#ff4444';
                            statusEl.style.background = 'rgba(255, 68, 68, 0.1)';
                            btnEl.disabled = false;
                            btnEl.textContent = '<?= __('Claim Reward') ?>';
                        }
                        clearInterval(countdownInterval);
                    }
                }, 1000);
            }

            async function redeemCommunityEvent(eventId, btnEl) {
                btnEl.disabled = true;
                btnEl.textContent = '<?= __('Preparing...') ?>';

                const overlay = document.getElementById('drop-animation-overlay');
                const box = document.getElementById('drop-item-box');
                const thankYouText = document.getElementById('thank-you-text');
                const countdownEl = document.getElementById('countdown-text');
                const statusEl = document.getElementById('redeem-status');
                statusEl.style.display = 'none';

                box.className = 'drop-item-box'; 

                thankYouText.style.animation = 'none';
                thankYouText.style.opacity = '0';

                const newBox = box.cloneNode(true);
                box.parentNode.replaceChild(newBox, box);
                overlay.style.display = 'flex';

                let count = 3;
                countdownEl.textContent = count;
                countdownEl.style.display = 'block';

                const countdownInterval = setInterval(async () => {
                    count--;
                    if (count > 0) {
                        countdownEl.textContent = count;
                        countdownEl.style.transform = 'scale(1.5)';
                        setTimeout(() => countdownEl.style.transform = 'scale(1)', 100);
                    } else if (count === 0) {
                        countdownEl.style.transform = 'scale(1.5)';
                        countdownEl.textContent = "<?= __('DROPPING!') ?>";
                        
                        try {
                            let payload = { event_id: eventId };
                            const bonusSelect = document.getElementById('ce_bonus_choice_' + eventId);
                            if (bonusSelect) {
                                if (!bonusSelect.value) {
                                    throw new Error('<?= __('Please select your Top 3 Bonus Reward first!') ?>');
                                }
                                payload.bonus_choice = bonusSelect.value;
                            }

                            const response = await fetch('/api/redeem_community.php', {
                                method: 'POST',
                                credentials: 'same-origin',
                                headers: { 
                                    'Content-Type': 'application/json',
                                    'X-CSRF-Token': window.getCSRFToken()
                                },
                                body: JSON.stringify(payload)
                            });
                            const data = await response.json();
                            if (response.ok && data.success) {
                                countdownEl.style.display = 'none';
                                thankYouText.textContent = "<?= __('REWARD CLAIMED!') ?>";
                                thankYouText.style.animation = 'textDrop 1.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards';

                                createFireworks();

                                setTimeout(() => {
                                    overlay.style.display = 'none';
                                    statusEl.textContent = data.message;
                                    statusEl.style.display = 'block';
                                    statusEl.className = 'alert-box success';
                                    statusEl.style.color = '#1eff64';
                                    btnEl.textContent = '<?= __('Claimed!') ?>';
                                    btnEl.style.background = 'rgba(255,255,255,0.1)';
                                    btnEl.style.color = 'rgba(255,255,255,0.5)';
                                    btnEl.style.borderColor = 'rgba(255,255,255,0.2)';
                                    setTimeout(() => { window.location.reload(); }, 2000);
                                }, 4000);
                            } else {
                                throw new Error(data.error || 'Failed to claim reward.');
                            }
                        } catch(e) {
                            clearInterval(countdownInterval);
                            overlay.style.display = 'none';
                            statusEl.textContent = '<?= __('Connection error: ') ?>' + e.message;
                            statusEl.style.display = 'block';
                            statusEl.className = 'alert-box';
                            statusEl.style.color = '#ff4444';
                            statusEl.style.background = 'rgba(255, 68, 68, 0.1)';
                            btnEl.disabled = false;
                            btnEl.textContent = '<?= __('Claim Community Reward') ?>';
                        }
                        clearInterval(countdownInterval);
                    }
                }, 1000);
            }

            function createFireworks() {
                const overlay = document.getElementById('drop-animation-overlay');
                const colors = ['#ff4444', '#33b5e5', '#00C851', '#ffaa00', '#aa66cc', '#ffffff'];

                for (let b = 0; b < 6; b++) {
                    setTimeout(() => {
                        const centerX = window.innerWidth / 2 + (Math.random() - 0.5) * 600;
                        const centerY = window.innerHeight / 2 + (Math.random() - 0.5) * 500 - 150;

                        for (let i = 0; i < 80; i++) {
                            const particle = document.createElement('div');
                            particle.style.position = 'absolute';
                            particle.style.left = centerX + 'px';
                            particle.style.top = centerY + 'px';
                            particle.style.width = (Math.random() * 8 + 4) + 'px';
                            particle.style.height = particle.style.width;
                            particle.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
                            particle.style.borderRadius = '50%';
                            particle.style.pointerEvents = 'none';
                            particle.style.zIndex = '9998';
                            particle.style.boxShadow = `0 0 15px ${particle.style.backgroundColor}, 0 0 30px ${particle.style.backgroundColor}`;

                            overlay.appendChild(particle);

                            const angle = Math.random() * Math.PI * 2;
                            const velocity = 100 + Math.random() * 300;
                            const tx = Math.cos(angle) * velocity;
                            const ty = Math.sin(angle) * velocity;

                            particle.animate([
                                { transform: 'translate(0,0) scale(1)', opacity: 1 },
                                { transform: `translate(${tx}px, ${ty}px) scale(0)`, opacity: 0 }
                            ], {
                                duration: 1000 + Math.random() * 800,
                                easing: 'cubic-bezier(0.25, 1, 0.5, 1)',
                                fill: 'forwards'
                            });

                            setTimeout(() => { if (particle.parentNode) particle.remove(); }, 2000);
                        }
                    }, b * 300);
                }
            }
            
            async function abandonBounty(pmId, btnEl) {
                if (!confirm("<?= __('Are you sure you want to abandon this quest? It will be removed from your active bounties completely.') ?>")) return;

                btnEl.disabled = true;
                btnEl.textContent = '<?= __('Abandoning...') ?>';

                try {
                    const response = await fetch('/api/abandon_bounty.php', {
                        method: 'POST',
                        credentials: 'same-origin',
                        headers: { 
                            'Content-Type': 'application/json',
                            'X-CSRF-Token': window.getCSRFToken()
                        },
                        body: JSON.stringify({ player_mission_id: pmId })
                    });
                    const data = await response.json();
                    if (response.ok && data.success) {
                        btnEl.textContent = '<?= __('Abandoned') ?>';
                        btnEl.style.background = 'rgba(255,255,255,0.1)';
                        btnEl.style.color = '#fff';
                        btnEl.style.borderColor = '#aaa';
                        setTimeout(() => { window.location.reload(); }, 1000);
                    } else {
                        throw new Error(data.error || '<?= __('Failed to abandon quest.') ?>');
                    }
                } catch(e) {
                    alert("Error: " + e.message);
                    btnEl.disabled = false;
                    btnEl.textContent = '<?= __('Abandon Quest') ?>';
                }
            }
            </script>

            <div class="section-header delay-1">
                <h2><?= __('Active Server Events') ?></h2>
            </div>
            
            <?php if (!empty($active_community_events)): ?>
                <div class="bounty-grid delay-2" style="margin-bottom: 3rem;">
                    <?php foreach ($active_community_events as $ce): ?>
                        <?php 
                        $pct = ($ce['current_progress'] / max(1, $ce['target_amount'])) * 100;
                        if ($pct > 100) $pct = 100;
                        ?>
                        <div class="bounty-card" style="border-color: #ffaa00;">
                            <div class="bounty-header">
                                <span class="bounty-player" style="color: #ffaa00; font-weight:bold; letter-spacing:1px; text-transform:uppercase;"><?= __('Community Event') ?></span>
                            </div>
                            <h3 class="bounty-title"><?= htmlspecialchars($ce['title']) ?></h3>
                            <p class="bounty-desc"><?= htmlspecialchars($ce['description']) ?></p>
                            
                            <div style="margin: 1.5rem 0;">
                                <div style="display:flex; justify-content:space-between; margin-bottom:5px; font-size:14px; color:#aaa;">
                                    <span><?= number_format($ce['current_progress']) ?> / <?= number_format($ce['target_amount']) ?></span>
                                    <span style="color:#ffaa00; font-weight:bold;"><?= floor($pct) ?>%</span>
                                </div>
                                <div style="width: 100%; height: 10px; background: rgba(0,0,0,0.5); border-radius: 5px; border: 1px solid #333; overflow:hidden;">
                                    <div style="width: <?= $pct ?>%; height: 100%; background: linear-gradient(90deg, #ffaa00, #ffea00); transition: width 0.5s;"></div>
                                </div>
                            </div>
                            
                            <div class="bounty-meta">
                                <div class="bounty-meta-row">
                                    <span class="bounty-meta-label"><?= __('Directive') ?></span>
                                    <span class="bounty-meta-val"><?= getClearObjective($ce['goal_type'], $ce['goal_target']) ?></span>
                                </div>
                                <div class="bounty-meta-row">
                                    <span class="bounty-meta-label"><?= __('Community Reward') ?></span>
                                    <span class="bounty-meta-val bounty-reward" style="color:#ffaa00;"><?= renderRewardString($ce['reward_item_string']) ?></span>
                                </div>
                                <?php if (!empty($ce['top_3_reward_item_string'])): ?>
                                <div class="bounty-meta-row" style="margin-top: 5px;">
                                    <span class="bounty-meta-label" style="color:#00ffcc;"><?= __('Top 3 Bonus') ?></span>
                                    <span class="bounty-meta-val bounty-reward" style="color:#00ffcc;"><?= renderRewardString($ce['top_3_reward_item_string']) ?></span>
                                </div>
                                <?php endif; ?>
                            </div>
                            
                            <?php if (!empty($top_contributors[$ce['id']])): ?>
                            <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid rgba(255,170,0,0.2);">
                                <h4 style="margin: 0 0 10px 0; font-size: 0.85rem; color: #aaa; text-transform: uppercase; letter-spacing: 1px;"><?= __('Current Top 3 Hunters') ?></h4>
                                <ul style="list-style: none; padding: 0; margin: 0; font-size: 0.9rem;">
                                    <?php foreach ($top_contributors[$ce['id']] as $idx => $tc): ?>
                                    <li style="display: flex; justify-content: space-between; margin-bottom: 5px; background: rgba(0,0,0,0.4); padding: 4px 8px; border-radius: 4px; border-left: 2px solid <?php echo ['#ffd700', '#c0c0c0', '#cd7f32'][$idx] ?? '#555'; ?>;">
                                        <span style="color: #fff;"><?= ($idx+1) ?>. <?= htmlspecialchars($tc['username']) ?></span>
                                        <span style="color: #ffaa00; font-weight: bold;"><?= number_format($tc['contribution_count']) ?></span>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <div class="section-header delay-1">
                <h2><?= __('Active Personal Bounties') ?></h2>
            </div>
            
            <?php if (empty($active_bounties)): ?>
                <div class="bounty-card" style="text-align: center; padding: 3rem;">
                    <h3 style="color: rgba(255,255,255,0.5);"><?= __('No active bounties at the moment. Check back soon!') ?></h3>
                </div>
            <?php else: ?>
                <div class="bounty-grid delay-2">
                    <?php foreach ($active_bounties as $b): ?>
                        <?php $is_mine = (isset($_SESSION['user']) && strtolower($b['username']) === strtolower($_SESSION['user']['username'])); ?>
                        <div class="bounty-card" <?= $is_mine ? 'style="border-color: #ffaa00; box-shadow: 0 0 15px rgba(255,170,0,0.15);"' : '' ?>>
                            <div class="bounty-header">
                                <span class="bounty-player" <?= $is_mine ? 'style="color:#ffaa00; font-weight:bold;"' : '' ?>><?= __('Hunter: ') ?><?= htmlspecialchars($b['username']) ?> <?= $is_mine ? '(You)' : '' ?></span>
                                <span class="bounty-status status-active"><?= __('Active') ?></span>
                            </div>
                            <h3 class="bounty-title"><?= htmlspecialchars($b['title']) ?></h3>
                            <p class="bounty-desc"><?= htmlspecialchars($b['description']) ?></p>
                            <div class="bounty-meta">
                                <div class="bounty-meta-row">
                                    <span class="bounty-meta-label"><?= __('Directive') ?></span>
                                    <span class="bounty-meta-val">
                                        <?= getClearObjective($b['goal_type'], $b['goal_target']) ?>
                                    </span>
                                </div>
                                <div class="bounty-meta-row">
                                    <span class="bounty-meta-label"><?= __('Reward') ?></span>
                                    <span class="bounty-meta-val bounty-reward"><?= renderRewardString($b['reward_item_string']) ?></span>
                                </div>
                            </div>
                            <?php if (isset($_SESSION['user']) && strtolower($b['username']) === strtolower($_SESSION['user']['username'])): ?>
                                <button onclick="abandonBounty(<?= $b['pm_id'] ?>, this)" class="dl-btn" style="width: 100%; margin-top: 1rem; background: rgba(255, 68, 68, 0.15); border-color: #ff4444; color: #ff4444; font-weight: bold; padding: 10px; box-shadow: none;"><?= __('Abandon Quest') ?></button>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>

        <!-- Right Column: Leaderboard -->
        <aside class="sidebar delay-3">
            <!-- Instructions Widget -->
            <div class="leaderboard-widget" style="margin-bottom: 2rem;">
                <h3 style="border-bottom-color: var(--pso-blue); color: var(--pso-blue);"><?= __('How to Play') ?></h3>
                <p style="font-size: 0.9rem; line-height:1.5; color: rgba(255,255,255,0.8);">
                    <?= __('The Game Master automatically generates specially curated bounties tailored specifically to your character\'s stats and classes.') ?>
                    <br><br>
                    <?= __('From time to time, special server-wide bounties appear alongside personal hunts.') ?>
                    <br><br>
                    <a href="rewards.php" style="color: var(--pso-orange); font-weight: 600;"><?= __('Rewards Guide') ?> →</a>
                </p>
            </div>

            <div class="leaderboard-widget">
                <h3><?= __('Top Hunters') ?></h3>
                <?php if (empty($leaderboard)): ?>
                    <p style="text-align:center; opacity:0.6; padding: 1rem;"><?= __('The leaderboard is waiting for its first legend.') ?></p>
                <?php else: ?>
                    <ul class="leaderboard-list">
                        <?php foreach ($leaderboard as $idx => $lb): ?>
                            <?php $rank = $idx + 1; ?>
                            <li class="rank-<?= $rank ?>">
                                <div class="rank-wrapper">
                                    <div class="rank-badge"><?= $rank ?></div>
                                    <span class="player-name"><?= htmlspecialchars($lb['username']) ?></span>
                                </div>
                                <span class="completion-count"><?= number_format($lb['completions']) ?></span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </aside>

    </div>
</main>

<?php include 'includes/footer.php'; ?>

<!-- Drop Animation Overlay -->
<div id="drop-animation-overlay" class="drop-overlay" style="display: none;">
    <div id="countdown-text" class="countdown-text"></div>
    <div class="thank-you-text" id="thank-you-text"><?= __('BOUNTY CLAIMED!') ?></div>
    <div class="drop-item-box" id="drop-item-box">
        <div class="drop-box-core">
            <div class="face front"></div>
            <div class="face back"></div>
            <div class="face right"></div>
            <div class="face left"></div>
            <div class="face top"></div>
            <div class="face bottom"></div>
        </div>
        <div class="drop-box-glow"></div>
    </div>
</div>

<style>
/* Custom Drop Animation */
.drop-overlay {
    position: fixed;
    top: 0; left: 0; width: 100vw; height: 100vh;
    background: rgba(0, 0, 0, 0.9);
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    perspective: 1000px;
}
.drop-item-box {
    position: relative;
    width: 60px;
    height: 60px;
    transform-style: preserve-3d;
    animation: dropIn 1s cubic-bezier(0.25, 1, 0.5, 1) forwards;
}
.thank-you-text {
    position: absolute;
    top: 20%;
    width: 100%;
    text-align: center;
    font-family: 'Share Tech Mono', 'Segoe UI', monospace;
    font-size: 4rem;
    color: #fff;
    text-shadow: 0 0 20px rgba(0, 255, 255, 1), 0 0 40px rgba(0, 255, 255, 0.8);
    z-index: 10000;
    opacity: 0;
    pointer-events: none;
}
.countdown-text {
    position: absolute;
    top: 40%;
    width: 100%;
    text-align: center;
    font-family: 'Share Tech Mono', 'Segoe UI', monospace;
    font-size: 8rem;
    color: #fff;
    text-shadow: 0 0 30px rgba(255, 255, 255, 1);
    z-index: 10001;
    transition: transform 0.2s ease;
    pointer-events: none;
}

.drop-box-core {
    width: 100%;
    height: 100%;
    position: relative;
    transform-style: preserve-3d;
    transform: rotateX(-30deg) rotateY(45deg);
    animation: spinBox 3s linear infinite;
}
.drop-box-core .face {
    position: absolute;
    width: 60px;
    height: 60px;
    background: rgba(255, 42, 42, 0.8);
    border: 2px solid #ffaaaa;
    box-shadow: inset 0 0 15px rgba(255,255,255,0.5);
    backface-visibility: inherit;
}
.drop-box-core .face.front  { transform: rotateY(  0deg) translateZ(30px); }
.drop-box-core .face.right  { transform: rotateY( 90deg) translateZ(30px); }
.drop-box-core .face.back   { transform: rotateY(180deg) translateZ(30px); }
.drop-box-core .face.left   { transform: rotateY(-90deg) translateZ(30px); }
.drop-box-core .face.top    { transform: rotateX( 90deg) translateZ(30px); }
.drop-box-core .face.bottom { transform: rotateX(-90deg) translateZ(30px); }
.drop-box-glow {
    position: absolute;
    top: 50%; left: 50%;
    width: 200px; height: 200px;
    background: radial-gradient(circle, rgba(255, 42, 42, 0.8) 0%, transparent 70%);
    transform: translate(-50%, -50%);
    opacity: 0;
    animation: glowBurst 1.5s 0.8s forwards;
}

@keyframes dropIn {
    0% { transform: translateY(-300px) scale(0.5); opacity: 0; }
    60% { transform: translateY(20px) scale(1.1); opacity: 1; }
    80% { transform: translateY(-10px) scale(0.95); }
    100% { transform: translateY(0) scale(1); opacity: 1; }
}
@keyframes textDrop {
    0% { transform: translateY(-100px) scale(0.8); opacity: 0; }
    100% { transform: translateY(0) scale(1); opacity: 1; }
}
@keyframes spinBox {
    from { transform: rotateX(-20deg) rotateY(0deg); }
    to { transform: rotateX(-20deg) rotateY(360deg); }
}
@keyframes glowBurst {
    0% { opacity: 0; transform: translate(-50%, -50%) scale(0.5); }
    50% { opacity: 1; transform: translate(-50%, -50%) scale(1.2); }
    100% { opacity: 0; transform: translate(-50%, -50%) scale(2); }
}
</style>
