<?php
/**
 * PSOBB Website: Bounty Board & Community Missions
 * 
 * Renders the active Hunter's Guild personal bounties and the server-wide 
 * community events. Interacts with `redeem_bounty.php` and `abandon_bounty.php`
 * securely using CSRF-protected AJAX calls.
 */
require_once __DIR__ . '/api/config.php';
require_once __DIR__ . '/api/functions.php';
start_secure_session();

// Global page variables mapped before headers
$page_title = 'Hunters Guild - Bounty Board';
$current_page = 'missions';
include 'includes/header.php';
require_once 'api/db.php';

$db = get_db();

// -------------------------------------------------------------------------
// 0. Fetch Pending Redemptions
// Fetches completed missions that have not yet had their rewards disbursed in-game.
// -------------------------------------------------------------------------
$pending_redemptions = [];
$account_id = $_SESSION['user']['account_id'] ?? 0;
if ($account_id) {
    $pr_res = $db->prepare("SELECT pm.id as pm_id, pm.character_name, m.title, m.description, m.goal_type, m.goal_target, m.reward_item_string 
                            FROM player_missions pm 
                            JOIN missions m ON pm.mission_id = m.id 
                            WHERE pm.account_id = :accId AND pm.status = 'ready_to_redeem' 
                            ORDER BY (m.goal_type = 'HARDCORE_MENTOR' OR m.goal_type = 'DIVERSE_PARTY_BOSS') DESC, pm.id DESC");
    $pr_res->bindValue(':accId', $account_id, SQLITE3_INTEGER);
    $pr_exec = $pr_res->execute();
    while ($row = $pr_exec->fetchArray(SQLITE3_ASSOC)) {
        $pending_redemptions[] = $row;
    }
}

// -------------------------------------------------------------------------
// 1. Fetch Global Top 10 Leaderboard
// Ranks players on the frontend based on the total aggregate of all completed bounties.
// -------------------------------------------------------------------------
$leaderboard = [];
$lb_res = $db->query("SELECT COALESCE(u.display_name, 'Hunter #' || u.account_id) as hunter_name, COUNT(pm.id) as completions 
                      FROM player_missions pm 
                      JOIN users u ON pm.account_id = u.account_id 
                      WHERE pm.status = 'completed' 
                      GROUP BY u.account_id 
                      ORDER BY completions DESC 
                      LIMIT 3");
while ($row = $lb_res->fetchArray(SQLITE3_ASSOC)) {
    $leaderboard[] = $row;
}

// -------------------------------------------------------------------------
// 2. Fetch Global Active Bounties Feed
// Populates the live feed of in-progress bounties dynamically generated by Gemini.
// -------------------------------------------------------------------------
$active_bounties = [];
$ab_query = "SELECT pm.id as pm_id, m.id as mission_id, pm.account_id as bounty_account_id, COALESCE(u.display_name, 'Hunter #' || u.account_id) as hunter_name, pm.character_name, m.title, m.description, m.goal_type, m.goal_target, m.reward_item_string 
             FROM player_missions pm 
             JOIN missions m ON pm.mission_id = m.id 
             JOIN users u ON pm.account_id = u.account_id 
             WHERE pm.status = 'in_progress' ";

if ($account_id) {
    // SQLite boolean expression: (u.account_id = X) evaluates to 1 or 0. Sorting DESC puts 1s at the top!
    $ab_query .= "ORDER BY (u.account_id = :accId) DESC, pm.id DESC";
    $ab_stmt = $db->prepare($ab_query);
    $ab_stmt->bindValue(':accId', $account_id, SQLITE3_INTEGER);
    $ab_res = $ab_stmt->execute();
} else {
    $ab_query .= "ORDER BY pm.id DESC";
    $ab_res = $db->query($ab_query);
}
while ($row = $ab_res->fetchArray(SQLITE3_ASSOC)) {
    $active_bounties[] = $row;
}

// -------------------------------------------------------------------------
// 3. Fetch Community Events (Active and Claimable) & User Contributions
// -------------------------------------------------------------------------
$active_community_events = [];
$claimable_community_events = [];

/**
 * Cache of the currently logged-in player's contribution statistics.
 * Mapped as: array(event_id => contribution_count)
 * Used to render personalized progress bars and dynamic reward tiers.
 */
$user_contributions = [];

if ($account_id) {
    // Retrieve the point telemetry for the active player across all community campaigns
    $uc_res = $db->prepare("SELECT event_id, contribution_count FROM community_event_participants WHERE account_id = :accId");
    $uc_res->bindValue(':accId', $account_id, SQLITE3_INTEGER);
    $uc_exec = $uc_res->execute();
    if ($uc_exec) {
        while ($uc_row = $uc_exec->fetchArray(SQLITE3_ASSOC)) {
            $user_contributions[$uc_row['event_id']] = $uc_row['contribution_count'];
        }
    }
}

// Get active events
$ce_res = $db->query("SELECT id, title, description, goal_type, goal_target, target_amount, current_progress, reward_item_string, top_3_reward_item_string
                      FROM community_events 
                      WHERE status = 'active'
                      ORDER BY id DESC");
$top_contributors = [];
while ($row = $ce_res->fetchArray(SQLITE3_ASSOC)) {
    $active_community_events[] = $row;
    
    // Fetch Top 3
    $top_stmt = $db->prepare("SELECT COALESCE(u.display_name, 'Hunter #' || u.account_id) as hunter_name, cep.contribution_count FROM community_event_participants cep JOIN users u ON cep.account_id = u.account_id WHERE cep.event_id = :eid ORDER BY cep.contribution_count DESC LIMIT 3");
    $top_stmt->bindValue(':eid', $row['id'], SQLITE3_INTEGER);
    $top_exec = $top_stmt->execute();
    while ($t_row = $top_exec->fetchArray(SQLITE3_ASSOC)) {
        $top_contributors[$row['id']][] = $t_row;
    }
}

// Get claimable events for the current user
if ($account_id) {
    $cc_res = $db->prepare("SELECT ce.id as event_id, ce.title, ce.description, ce.reward_item_string, ce.top_3_reward_item_string, cep.contribution_count
                            FROM community_events ce
                            JOIN community_event_participants cep ON ce.id = cep.event_id
                            WHERE ce.status = 'completed' AND cep.account_id = :accId AND cep.reward_claimed = 0");
    $cc_res->bindValue(':accId', $account_id, SQLITE3_INTEGER);
    $cc_exec = $cc_res->execute();
    while ($row = $cc_exec->fetchArray(SQLITE3_ASSOC)) {
        $top3_stmt = $db->prepare("SELECT account_id FROM community_event_participants WHERE event_id = :eid ORDER BY contribution_count DESC LIMIT 3");
        $top3_stmt->bindValue(':eid', $row['event_id'], SQLITE3_INTEGER);
        $top3_res = $top3_stmt->execute();
        $is_top_3 = false;
        while ($t3 = $top3_res->fetchArray(SQLITE3_ASSOC)) {
            if ($t3['account_id'] == $account_id) {
                $is_top_3 = true;
                break;
            }
        }
        $row['is_top_3'] = $is_top_3;
        $claimable_community_events[] = $row;
    }
}

?>

<link rel="stylesheet" href="css/missions.css">

<main class="container missions-wide">
    <section class="missions-hero animate-fade-in">
        <h1><?= __('Hunters Guild Active Roster') ?></h1>
        <p><?= __('The official Pioneer 2 Bounty Board. Complete unique, specially curated quests to earn meseta, rare items, and global recognition.') ?></p>
    </section>

    <!-- Global AJAX Redemption Alert Box -->
    <div id="redeem-status" class="alert-box success" style="display: none; margin-bottom: 2rem;"></div>

    <!-- Active Server Events (Community Campaigns) -->
    <?php if (!empty($active_community_events)): ?>
        <div class="dashboard-section accent-orange">
            <div class="section-header delay-1">
                <h2>🔥 <?= __('Active Server Events') ?></h2>
            </div>
            
            <!-- Widescreen Event Reward Scaling Tier Chart Banner -->
            <div class="reward-scaling-banner">
                <div class="reward-scaling-intro">
                    <h3>🎁 <?= __('Event Reward Scaling') ?></h3>
                    <p><?= __('Server-wide community events now feature prestigious, dynamic reward scaling based on your personal contribution points:') ?></p>
                </div>
                <div class="reward-scaling-grid-container">
                    <div class="reward-scaling-grid">
                        <div class="reward-scaling-item">
                            <span class="reward-scaling-item-title"><?= __('Base Reward') ?></span>
                            <span class="reward-scaling-item-desc"><?= __('1x Random Level-Fit Rare Drop + 5,000 Meseta') ?></span>
                        </div>
                        <div class="reward-scaling-item">
                            <span class="reward-scaling-item-title"><?= __('Drop Escalation') ?></span>
                            <span class="reward-scaling-item-desc"><?= __('+1 Rare Drop & +5,000 Meseta for every 50 points earned') ?></span>
                        </div>
                        <div class="reward-scaling-item">
                            <span class="reward-scaling-item-title"><?= __('Ultimate Cap') ?></span>
                            <span class="reward-scaling-item-desc"><?= __('Capped at a massive 10x Rare Drops + 50,000 Meseta (at 450+ points)') ?></span>
                        </div>
                        <div class="reward-scaling-item">
                            <span class="reward-scaling-item-title"><?= __('Leaderboard Bonus') ?></span>
                            <span class="reward-scaling-item-desc"><?= __('The Top 3 leaderboard champions receive a grand 100,000 Meseta cash prize!') ?></span>
                        </div>
                    </div>
                    <div class="reward-scaling-note">
                        * <?= __('Note: Random Rare drops are dynamically drawn fit for your character class and level at the moment of claiming!') ?>
                    </div>
                </div>
            </div>
            
            <?php foreach ($active_community_events as $ce): ?>
                <?php 
                $pct = ($ce['current_progress'] / max(1, $ce['target_amount'])) * 100;
                if ($pct > 100) $pct = 100;
                ?>
                <div class="pso-hud-card-wide">
                    <div class="pso-hud-card-wide-grid">
                        
                        <!-- Column 1: Event Details & Progress -->
                        <div class="pso-hud-card-wide-col">
                            <span class="bounty-player" style="color: #ffaa00; font-weight:bold; letter-spacing:1px; text-transform:uppercase; margin-bottom: 0.4rem; display: block;"><?= __('Community Event') ?></span>
                            <h3 class="bounty-title" style="margin-bottom: 0.5rem;"><?= htmlspecialchars(__($ce['title'])) ?></h3>
                            
                            <?php 
                                if ($ce['goal_target'] === 'DIGITAL_BLASPHEMY') {
                                    $display_desc = __('Corrupted cybernetic mainframes are spawning simulations across Ragol! Cooperate server-wide to defeat the simulated threats and earn prestigious rare drops fitted for your character class and level.');
                                    $display_desc = str_replace(
                                        [__('simulations'), __('Pioneer 2'), __('Vol Opt'), __('Gol Dragon'), __('Shambertin')], 
                                        ['<strong>' . __('simulations') . '</strong>', '<strong>' . __('Pioneer 2') . '</strong>', '<strong>Vol Opt</strong>', '<strong>Gol Dragon</strong>', '<strong>Shambertin</strong>'], 
                                        $display_desc
                                    );
                                } else {
                                    $bolded_desc = htmlspecialchars(__($ce['description']));
                                    $keywords = [
                                        'Vol Opt' => '<strong>Vol Opt</strong>',
                                        'Gol Dragon' => '<strong>Gol Dragon</strong>',
                                        'Shambertin' => '<strong>Shambertin</strong>',
                                        '3 random rare drops' => '<strong style="color: #ffaa00;">3 random rare drops</strong>',
                                        'difficulty bonuses' => '<strong>difficulty bonuses</strong>',
                                        'cooperate server-wide' => '<strong style="color: #ffaa00;">cooperate server-wide</strong>'
                                    ];
                                    foreach ($keywords as $word => $replacement) {
                                        $bolded_desc = str_ireplace($word, $replacement, $bolded_desc);
                                    }
                                    $display_desc = $bolded_desc;
                                }
                            ?>
                            <p class="bounty-desc" style="margin-bottom: 1rem; line-height: 1.5; color: rgba(224, 240, 255, 0.85);"><?= $display_desc ?></p>
                            
                            <div style="margin-top: auto;">
                                <div style="display:flex; justify-content:space-between; margin-bottom:5px; font-size:0.8rem; color:rgba(255,255,255,0.6);">
                                    <span><?= number_format($ce['current_progress']) ?> / <?= number_format($ce['target_amount']) ?></span>
                                    <span style="color:#ffaa00; font-weight:bold;"><?= floor($pct) ?>%</span>
                                </div>
                                <div class="pso-progress-container">
                                    <div class="pso-progress-bar" style="width: <?= $pct ?>%; --progress-start: #ffaa00; --progress-end: #ffea00; --progress-glow: rgba(255,170,0,0.45);"></div>
                                </div>
                            </div>
                        </div>

                        <!-- Column 2: Objectives & Event Rewards -->
                        <div class="pso-hud-card-wide-col">
                            <span class="bounty-player" style="color: #ffaa00; font-weight:bold; letter-spacing:1px; text-transform:uppercase; margin-bottom: 0.5rem; display: block;"><?= __('Operations Directive') ?></span>
                            
                            <div class="bounty-meta" style="display: flex; flex-direction: column; gap: 0.75rem; padding: 0.85rem;">
                                <?php if ($ce['goal_target'] === 'DIGITAL_BLASPHEMY'): ?>
                                    <!-- Tailored Objective Breakdown for Digital Blasphemy -->
                                    <div class="hud-objective-breakdown">
                                        <div class="hud-breakdown-section">
                                            <span class="hud-breakdown-header"><?= __('Target Boss Points') ?></span>
                                            <div class="hud-breakdown-badges">
                                                <div class="hud-badge-pill border-orange">
                                                    <span class="hud-pill-name">Vol Opt (Ep1)</span>
                                                    <span class="hud-pill-val color-orange">+1 Pt</span>
                                                </div>
                                                <div class="hud-badge-pill border-orange">
                                                    <span class="hud-pill-name">Gol Dragon (Ep2)</span>
                                                    <span class="hud-pill-val color-orange">+2 Pts</span>
                                                </div>
                                                <div class="hud-badge-pill border-orange">
                                                    <span class="hud-pill-name">Shambertin (Ep4)</span>
                                                    <span class="hud-pill-val color-orange">+3 Pts</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="hud-breakdown-section">
                                            <span class="hud-breakdown-header"><?= __('Difficulty Modifiers') ?></span>
                                            <div class="hud-breakdown-badges">
                                                <div class="hud-badge-pill border-cyan">
                                                    <span class="hud-pill-name">Hard</span>
                                                    <span class="hud-pill-val color-cyan">+1</span>
                                                </div>
                                                <div class="hud-badge-pill border-cyan">
                                                    <span class="hud-pill-name">VHard</span>
                                                    <span class="hud-pill-val color-cyan">+2</span>
                                                </div>
                                                <div class="hud-badge-pill border-cyan">
                                                    <span class="hud-pill-name">Ultimate</span>
                                                    <span class="hud-pill-val color-cyan">+3</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <!-- Standard Objective Display -->
                                    <div class="bounty-meta-row" style="flex-direction: column; align-items: flex-start; gap: 4px;">
                                        <span class="bounty-meta-label"><?= __('Directive') ?></span>
                                        <span class="bounty-meta-val" style="color: #ffffff; text-align: left; max-width: 100%; font-size: 0.9rem;"><?= getClearObjective($ce['goal_type'], $ce['goal_target'], $ce['title'], $ce['description']) ?></span>
                                    </div>
                                <?php endif; ?>

                                <!-- Event Rewards and Bonuses Chips -->
                                <div style="display: flex; flex-direction: column; gap: 0.5rem; border-top: 1px dashed rgba(255,255,255,0.08); padding-top: 0.6rem; margin-top: 0.25rem;">
                                    <div class="bounty-meta-row" style="align-items: center;">
                                        <span class="bounty-meta-label"><?= __('Community Reward') ?></span>
                                        <span class="bounty-meta-val bounty-reward" style="font-size: 0.95rem;"><?= renderRewardString($ce['reward_item_string']) ?></span>
                                    </div>
                                    
                                    <?php if (!empty($ce['top_3_reward_item_string'])): ?>
                                        <div class="bounty-meta-row" style="flex-direction: column; align-items: flex-start; gap: 6px;">
                                            <span class="bounty-meta-label" style="color:#00ffcc; font-weight: 500;"><?= __('Top 3 Bonus Choice') ?></span>
                                            <div style="display: flex; flex-wrap: wrap; gap: 6px; width: 100%;">
                                                <?php 
                                                    $bonuses = explode('|', $ce['top_3_reward_item_string']);
                                                    foreach ($bonuses as $bonus): 
                                                        $bonus = trim($bonus);
                                                ?>
                                                    <span class="hud-reward-chip"><?= htmlspecialchars($bonus) ?></span>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>

                        <!-- Column 3: Telemetry & Leaderboard -->
                        <div class="pso-hud-card-wide-col">
                            <span class="bounty-player" style="color: #ffaa00; font-weight:bold; letter-spacing:1px; text-transform:uppercase; margin-bottom: 0.5rem; display: block;"><?= __('Telemetry Readings') ?></span>
                            
                            <?php if (!empty($top_contributors[$ce['id']])): ?>
                            <div class="event-mini-leaderboard" style="margin-top: 0; padding-top: 0; border-top: none; margin-bottom: 0.75rem;">
                                <h4 style="margin-bottom: 0.5rem; font-size: 0.78rem;"><?= __('Current Top 3 Hunters') ?></h4>
                                <ul>
                                    <?php foreach ($top_contributors[$ce['id']] as $idx => $tc): ?>
                                    <li class="rank-sub-<?= ($idx+1) ?>">
                                        <span class="player-name"><?= ($idx+1) ?>. <?= htmlspecialchars($tc['hunter_name']) ?></span>
                                        <span class="score-val"><?= number_format($tc['contribution_count']) ?></span>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <?php endif; ?>

                            <!-- Personalized Reward Status Board -->
                            <?php if ($account_id): ?>
                                <?php 
                                $user_contrib = $user_contributions[$ce['id']] ?? 0;
                                $is_top_3 = false;
                                if (!empty($top_contributors[$ce['id']])) {
                                    foreach ($top_contributors[$ce['id']] as $tc) {
                                        if (isset($_SESSION['user']['username']) && $tc['hunter_name'] === $_SESSION['user']['username']) {
                                            $is_top_3 = true;
                                            break;
                                        }
                                    }
                                }
                                
                                $num_rares = 1 + floor($user_contrib / 50);
                                if ($num_rares > 10) $num_rares = 10;
                                
                                if ($is_top_3) {
                                    $meseta_val = 100000;
                                } else {
                                    $meseta_val = 5000 + (floor($user_contrib / 50) * 5000);
                                    if ($meseta_val > 50000) $meseta_val = 50000;
                                }
                                
                                $next_tier = (floor($user_contrib / 50) + 1) * 50;
                                $sub_pct = (($user_contrib % 50) / 50) * 100;
                                if ($user_contrib >= 450) {
                                    $sub_pct = 100;
                                    $next_tier = 450;
                                }
                                ?>
                                <div class="contribution-box" style="margin-top: auto; padding: 0.75rem; font-size: 0.78rem;">
                                    <h4 style="margin-bottom: 0.6rem; font-size: 0.85rem;">
                                        <span>📊 <?= __('Your Status') ?></span>
                                        <span class="contribution-badge" style="padding: 1px 6px; font-size: 0.72rem;"><?= number_format($user_contrib) ?> <?= __('pts') ?></span>
                                    </h4>
                                    
                                    <div class="contribution-readout" style="font-size: 0.78rem; margin-bottom: 10px; line-height: 1.45;">
                                        <strong><?= __('Current Tier:') ?></strong> <span style="color:#00ffcc; font-weight:bold;"><?= $num_rares ?>x Rare Drop<?= $num_rares > 1 ? 's' : '' ?></span> + <span style="color:#ffaa00; font-weight:bold;"><?= number_format($meseta_val) ?> Meseta</span>
                                        <?php if ($is_top_3): ?>
                                            <span style="display:block; margin-top:2px; color:#ffd700; font-weight:bold;">🏆 <?= __('Leaderboard Champion prize!') ?></span>
                                        <?php endif; ?>
                                    </div>
                                    
                                    <?php if ($user_contrib < 450): ?>
                                        <div class="contribution-milestone-text" style="font-size: 0.72rem; margin-bottom: 0.3rem;">
                                            <span><?= __('Next Tier (+1 Drop):') ?></span>
                                            <strong><?= ($user_contrib % 50) ?> / 50</strong>
                                        </div>
                                        <div class="pso-progress-container" style="height: 6px;">
                                            <div class="pso-progress-bar" style="width: <?= $sub_pct ?>%; --progress-start: #00ffcc; --progress-end: #00ffff; --progress-glow: rgba(0, 255, 204, 0.45);"></div>
                                        </div>
                                    <?php else: ?>
                                        <div style="font-size: 0.72rem; color: #00ffcc; font-weight:bold; display: flex; align-items: center; gap: 4px;">
                                            🌟 <?= __('MAX TIER REACHED!') ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>

                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <div class="missions-container">
        
        <!-- Left Column: Bounties -->
        <div>
            <!-- Consolidated Guild Claim Center (Ready to Claim) -->
            <?php if (!empty($pending_redemptions) || !empty($claimable_community_events)): ?>
                <div class="guild-claim-center dashboard-section delay-1">
                    <div class="guild-claim-center-header">
                        <h3>🎁 <?= __('Guild Claim Center') ?></h3>
                    </div>
                    
                    <!-- Pending Personal Redemptions -->
                    <?php if (!empty($pending_redemptions)): ?>
                        <?php foreach ($pending_redemptions as $r): ?>
                            <?php 
                                $is_team = ($r['goal_type'] === 'HARDCORE_MENTOR' || $r['goal_type'] === 'DIVERSE_PARTY_BOSS');
                                $voucher_class = $is_team ? 'accent-purple' : 'accent-green';
                            ?>
                            <div class="reward-voucher <?= $voucher_class ?>">
                                <div class="voucher-left">
                                    <span class="voucher-tag"><?= $is_team ? __('Team Mission Complete!') : __('Mission Complete!') ?></span>
                                    <h4 class="voucher-title"><?= htmlspecialchars($r['title']) ?></h4>
                                    <p class="voucher-desc"><?= htmlspecialchars($r['description']) ?></p>
                                    <span style="font-size: 0.75rem; color: rgba(255,255,255,0.4); margin-top: 4px; display: inline-block;">
                                        <?= __('Character:') ?> <strong><?= htmlspecialchars($r['character_name'] ?? 'Account Wide') ?></strong>
                                    </span>
                                </div>
                                <div class="voucher-right">
                                    <div class="voucher-reward-box">
                                        <span class="voucher-reward-label"><?= __('Reward') ?></span>
                                        <span class="voucher-reward-val"><?= renderRewardString($r['reward_item_string']) ?></span>
                                    </div>
                                    <button onclick="redeemBounty(<?= $r['pm_id'] ?>, this)" class="dl-btn voucher-action-btn"><?= __('Claim Reward') ?></button>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                        
                    <!-- Claimable Community Events -->
                    <?php if (!empty($claimable_community_events)): ?>
                        <?php foreach ($claimable_community_events as $ce): ?>
                            <div class="reward-voucher accent-orange">
                                <div class="voucher-left">
                                    <span class="voucher-tag"><?= __('Server Event Completed!') ?></span>
                                    <h4 class="voucher-title"><?= htmlspecialchars(__($ce['title'])) ?></h4>
                                    <p class="voucher-desc"><?= htmlspecialchars(__($ce['description'])) ?></p>
                                    
                                    <?php 
                                        if ($ce['is_top_3'] && !empty($ce['top_3_reward_item_string'])) {
                                            $choices = array_map('trim', explode('|', $ce['top_3_reward_item_string']));
                                            if (count($choices) > 1): 
                                    ?>
                                                <div style="margin-top: 10px; max-width: 320px;">
                                                    <label style="font-size: 0.72rem; color: #00ffcc; text-transform: uppercase; font-weight: bold; display: block; margin-bottom: 4px;"><?= __('Top 3 Bonus Selection') ?></label>
                                                    <select id="ce_bonus_choice_<?= $ce['event_id'] ?>" style="width:100%; padding:6px; background:rgba(0,0,0,0.8); border:1px solid #00ffcc; color:#00ffcc; border-radius:4px; font-size:0.8rem;">
                                                        <option value="">-- <?= __('Select Your Bonus Reward') ?> --</option>
                                                        <?php foreach($choices as $c): ?>
                                                            <option value="<?= htmlspecialchars($c) ?>"><?= htmlspecialchars($c) ?></option>
                                                        <?php endforeach; ?>
                                                    </select>
                                                </div>
                                            <?php else: ?>
                                                <div style="margin-top: 6px; font-size: 0.78rem; color:#00ffcc;">
                                                    <strong>🏆 <?= __('Top 3 Bonus:') ?></strong> <?= renderRewardString($ce['top_3_reward_item_string']) ?>
                                                </div>
                                    <?php 
                                            endif; 
                                        } 
                                    ?>
                                </div>
                                <div class="voucher-right">
                                    <div class="voucher-reward-box">
                                        <span class="voucher-reward-label"><?= __('Your Contribution') ?> / <?= __('Reward') ?></span>
                                        <span class="voucher-reward-val" style="margin-bottom: 2px; color: rgba(255,255,255,0.7); font-size: 0.75rem;"><?= number_format($ce['contribution_count']) ?> pts</span>
                                        <span class="voucher-reward-val"><?= renderRewardString($ce['reward_item_string']) ?></span>
                                    </div>
                                    <button onclick="redeemCommunityEvent(<?= $ce['event_id'] ?>, this)" class="dl-btn voucher-action-btn"><?= __('Claim Reward') ?></button>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <!-- Interactive Scripting Block -->
            <script>
            async function redeemBounty(pmId, btnEl) {
                btnEl.disabled = true;
                btnEl.textContent = '<?= __('Preparing...') ?>';

                const overlay = document.getElementById('drop-animation-overlay');
                const box = document.getElementById('drop-item-box');
                const thankYouText = document.getElementById('thank-you-text');
                const countdownEl = document.getElementById('countdown-text');
                const statusEl = document.getElementById('redeem-status');
                statusEl.style.display = 'none';

                // Always use default red box for rare bounty rewards
                box.className = 'drop-item-box'; 

                thankYouText.style.animation = 'none';
                thankYouText.style.opacity = '0';

                const newBox = box.cloneNode(true);
                box.parentNode.replaceChild(newBox, box);

                overlay.style.display = 'flex';

                let count = 3;
                countdownEl.textContent = count;
                countdownEl.style.display = 'block';

                const countdownInterval = setInterval(async () => {
                    count--;
                    if (count > 0) {
                        countdownEl.textContent = count;
                        countdownEl.style.transform = 'scale(1.5)';
                        setTimeout(() => countdownEl.style.transform = 'scale(1)', 100);
                    } else if (count === 0) {
                        countdownEl.style.transform = 'scale(1.5)';
                        countdownEl.textContent = "<?= __('DROPPING!') ?>";
                        
                        try {
                            const response = await fetch('/api/redeem_bounty.php', {
                                method: 'POST',
                                credentials: 'same-origin',
                                headers: { 
                                    'Content-Type': 'application/json',
                                    'X-CSRF-Token': window.getCSRFToken()
                                },
                                body: JSON.stringify({ player_mission_id: pmId })
                            });
                            const data = await response.json();
                            if (response.ok && data.success) {
                                countdownEl.style.display = 'none';
                                thankYouText.textContent = "<?= __('BOUNTY CLAIMED!') ?>";
                                thankYouText.style.animation = 'textDrop 1.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards';

                                createFireworks();

                                setTimeout(() => {
                                    overlay.style.display = 'none';
                                    statusEl.textContent = data.message;
                                    statusEl.style.display = 'block';
                                    statusEl.className = 'alert-box success';
                                    statusEl.style.color = '#1eff64';
                                    statusEl.style.borderColor = '#1eff64';
                                    btnEl.textContent = '<?= __('Claimed!') ?>';
                                    btnEl.style.background = 'rgba(255,255,255,0.1)';
                                    btnEl.style.borderColor = 'rgba(255,255,255,0.2)';
                                    btnEl.style.color = 'rgba(255,255,255,0.5)';
                                    setTimeout(() => { window.location.reload(); }, 2000);
                                }, 4000);
                            } else {
                                throw new Error(data.error || 'Failed to claim reward.');
                            }
                        } catch(e) {
                            clearInterval(countdownInterval);
                            overlay.style.display = 'none';
                            statusEl.textContent = '<?= __('Connection error: ') ?>' + e.message;
                            statusEl.style.display = 'block';
                            statusEl.className = 'alert-box';
                            statusEl.style.color = '#ff4444';
                            statusEl.style.borderColor = '#ff4444';
                            statusEl.style.background = 'rgba(255, 68, 68, 0.1)';
                            btnEl.disabled = false;
                            btnEl.textContent = '<?= __('Claim Reward') ?>';
                        }
                        clearInterval(countdownInterval);
                    }
                }, 1000);
            }

            async function redeemCommunityEvent(eventId, btnEl) {
                btnEl.disabled = true;
                btnEl.textContent = '<?= __('Preparing...') ?>';

                const overlay = document.getElementById('drop-animation-overlay');
                const box = document.getElementById('drop-item-box');
                const thankYouText = document.getElementById('thank-you-text');
                const countdownEl = document.getElementById('countdown-text');
                const statusEl = document.getElementById('redeem-status');
                statusEl.style.display = 'none';

                box.className = 'drop-item-box'; 

                thankYouText.style.animation = 'none';
                thankYouText.style.opacity = '0';

                const newBox = box.cloneNode(true);
                box.parentNode.replaceChild(newBox, box);
                overlay.style.display = 'flex';

                let count = 3;
                countdownEl.textContent = count;
                countdownEl.style.display = 'block';

                const countdownInterval = setInterval(async () => {
                    count--;
                    if (count > 0) {
                        countdownEl.textContent = count;
                        countdownEl.style.transform = 'scale(1.5)';
                        setTimeout(() => countdownEl.style.transform = 'scale(1)', 100);
                    } else if (count === 0) {
                        countdownEl.style.transform = 'scale(1.5)';
                        countdownEl.textContent = "<?= __('DROPPING!') ?>";
                        
                        try {
                            let payload = { event_id: eventId };
                            const bonusSelect = document.getElementById('ce_bonus_choice_' + eventId);
                            if (bonusSelect) {
                                if (!bonusSelect.value) {
                                    throw new Error('<?= __('Please select your Top 3 Bonus Reward first!') ?>');
                                }
                                payload.bonus_choice = bonusSelect.value;
                            }

                            const response = await fetch('/api/redeem_community.php', {
                                method: 'POST',
                                credentials: 'same-origin',
                                headers: { 
                                    'Content-Type': 'application/json',
                                    'X-CSRF-Token': window.getCSRFToken()
                                },
                                body: JSON.stringify(payload)
                            });
                            const data = await response.json();
                            if (response.ok && data.success) {
                                countdownEl.style.display = 'none';
                                thankYouText.textContent = "<?= __('REWARD CLAIMED!') ?>";
                                thankYouText.style.animation = 'textDrop 1.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards';

                                createFireworks();

                                setTimeout(() => {
                                    overlay.style.display = 'none';
                                    statusEl.textContent = data.message;
                                    statusEl.style.display = 'block';
                                    statusEl.className = 'alert-box success';
                                    statusEl.style.color = '#1eff64';
                                    btnEl.textContent = '<?= __('Claimed!') ?>';
                                    btnEl.style.background = 'rgba(255,255,255,0.1)';
                                    btnEl.style.color = 'rgba(255,255,255,0.5)';
                                    btnEl.style.borderColor = 'rgba(255,255,255,0.2)';
                                    setTimeout(() => { window.location.reload(); }, 2000);
                                }, 4000);
                            } else {
                                throw new Error(data.error || 'Failed to claim reward.');
                            }
                        } catch(e) {
                            clearInterval(countdownInterval);
                            overlay.style.display = 'none';
                            statusEl.textContent = '<?= __('Connection error: ') ?>' + e.message;
                            statusEl.style.display = 'block';
                            statusEl.className = 'alert-box';
                            statusEl.style.color = '#ff4444';
                            statusEl.style.background = 'rgba(255, 68, 68, 0.1)';
                            btnEl.disabled = false;
                            btnEl.textContent = '<?= __('Claim Community Reward') ?>';
                        }
                        clearInterval(countdownInterval);
                    }
                }, 1000);
            }

            function createFireworks() {
                const overlay = document.getElementById('drop-animation-overlay');
                const colors = ['#ff4444', '#33b5e5', '#00C851', '#ffaa00', '#aa66cc', '#ffffff'];

                for (let b = 0; b < 6; b++) {
                    setTimeout(() => {
                        const centerX = window.innerWidth / 2 + (Math.random() - 0.5) * 600;
                        const centerY = window.innerHeight / 2 + (Math.random() - 0.5) * 500 - 150;

                        for (let i = 0; i < 80; i++) {
                            const particle = document.createElement('div');
                            particle.style.position = 'absolute';
                            particle.style.left = centerX + 'px';
                            particle.style.top = centerY + 'px';
                            particle.style.width = (Math.random() * 8 + 4) + 'px';
                            particle.style.height = particle.style.width;
                            particle.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
                            particle.style.borderRadius = '50%';
                            particle.style.pointerEvents = 'none';
                            particle.style.zIndex = '9998';
                            particle.style.boxShadow = `0 0 15px ${particle.style.backgroundColor}, 0 0 30px ${particle.style.backgroundColor}`;

                            overlay.appendChild(particle);

                            const angle = Math.random() * Math.PI * 2;
                            const velocity = 100 + Math.random() * 300;
                            const tx = Math.cos(angle) * velocity;
                            const ty = Math.sin(angle) * velocity;

                            particle.animate([
                                { transform: 'translate(0,0) scale(1)', opacity: 1 },
                                { transform: `translate(${tx}px, ${ty}px) scale(0)`, opacity: 0 }
                            ], {
                                duration: 1000 + Math.random() * 800,
                                easing: 'cubic-bezier(0.25, 1, 0.5, 1)',
                                fill: 'forwards'
                            });

                            setTimeout(() => { if (particle.parentNode) particle.remove(); }, 2000);
                        }
                    }, b * 300);
                }
            }
            
            async function abandonBounty(pmId, btnEl) {
                if (!confirm("<?= __('Are you sure you want to abandon this quest? It will be removed from your active bounties completely.') ?>")) return;

                btnEl.disabled = true;
                btnEl.textContent = '<?= __('Abandoning...') ?>';

                try {
                    const response = await fetch('/api/abandon_bounty.php', {
                        method: 'POST',
                        credentials: 'same-origin',
                        headers: { 
                            'Content-Type': 'application/json',
                            'X-CSRF-Token': window.getCSRFToken()
                        },
                        body: JSON.stringify({ player_mission_id: pmId })
                    });
                    const data = await response.json();
                    if (response.ok && data.success) {
                        btnEl.textContent = '<?= __('Abandoned') ?>';
                        btnEl.style.background = 'rgba(255,255,255,0.1)';
                        btnEl.style.color = '#fff';
                        btnEl.style.borderColor = '#aaa';
                        setTimeout(() => { window.location.reload(); }, 1000);
                    } else {
                        throw new Error(data.error || '<?= __('Failed to abandon quest.') ?>');
                    }
                } catch(e) {
                    alert("Error: " + e.message);
                    btnEl.disabled = false;
                    btnEl.textContent = '<?= __('Abandon Quest') ?>';
                }
            }
            </script>



            <!-- Active Personal Bounties -->
            <div class="dashboard-section accent-cyan">
                <div class="section-header delay-1">
                    <h2>⚔️ <?= __('Active Personal Bounties') ?></h2>
                </div>
                
                <?php if (empty($active_bounties)): ?>
                    <div class="pso-hud-card" style="text-align: center; padding: 3rem;">
                        <h3 style="color: rgba(255,255,255,0.4);"><?= __('No active bounties at the moment. Check back soon!') ?></h3>
                    </div>
                <?php else: ?>
                    <div class="bounty-grid delay-2">
                        <?php foreach ($active_bounties as $b): ?>
                            <?php 
                                $is_mine = (isset($_SESSION['user']) && $b['bounty_account_id'] == $_SESSION['user']['account_id']); 
                                $is_team = ($b['goal_type'] === 'HARDCORE_MENTOR' || $b['goal_type'] === 'DIVERSE_PARTY_BOSS');
                                
                                $card_class = 'pso-hud-card';
                                if ($is_team) {
                                    $card_class .= ' accent-purple';
                                } elseif ($is_mine) {
                                    $card_class .= ' accent-orange';
                                } else {
                                    $card_class .= ' accent-cyan';
                                }
                            ?>
                            <div class="<?= $card_class ?>">
                                <div class="bounty-header">
                                    <span class="bounty-player" <?= ($is_mine && !$is_team) ? 'style="color:#ffaa00; font-weight:bold;"' : '' ?>>
                                        <?= __('Hunter: ') ?><?= htmlspecialchars($b['hunter_name']) ?> 
                                        <span style="font-weight:normal; font-size:0.8em; opacity:0.6;">(<?= htmlspecialchars($b['character_name'] ?? 'Account Wide') ?>)</span> 
                                        <?= $is_mine ? '(You)' : '' ?>
                                    </span>
                                    <?php if ($is_team): ?>
                                        <span class="bounty-status" style="background: rgba(199, 125, 255, 0.12); color: #e0aaff; border: 1px solid rgba(199, 125, 255, 0.3);"><?= __('Team Bounty') ?></span>
                                    <?php else: ?>
                                        <span class="bounty-status"><?= __('Personal Bounty') ?></span>
                                    <?php endif; ?>
                                </div>
                                <h3 class="bounty-title"><?= htmlspecialchars($b['title']) ?></h3>
                                <p class="bounty-desc"><?= htmlspecialchars($b['description']) ?></p>
                                <div class="bounty-meta">
                                    <div class="bounty-meta-row">
                                        <span class="bounty-meta-label"><?= __('Directive') ?></span>
                                        <span class="bounty-meta-val" style="color: #ffffff;"><?= getClearObjective($b['goal_type'], $b['goal_target'], $b['title'], $b['description']) ?></span>
                                    </div>
                                    <div class="bounty-meta-row">
                                        <span class="bounty-meta-label"><?= __('Reward') ?></span>
                                        <span class="bounty-meta-val bounty-reward"><?= renderRewardString($b['reward_item_string']) ?></span>
                                    </div>
                                </div>
                                <?php if ($is_mine): ?>
                                    <div style="margin-top: 1.25rem; display: flex; flex-direction: column; gap: 0.5rem; width: 100%;">
                                        <?php if ($is_team): ?>
                                            <a href="lfg.php?bounty_id=<?= $b['mission_id'] ?>" class="dl-btn" style="display: block; text-align: center; width: 100%; font-size: 0.95rem; font-weight: bold; padding: 10px; box-sizing: border-box; text-decoration: none; background: rgba(0, 255, 255, 0.15); border-color: #00ffff; color: #00ffff;"><i class="fas fa-bullhorn"></i> <?= __('Post to LFG') ?></a>
                                        <?php endif; ?>
                                        <button onclick="abandonBounty(<?= $b['pm_id'] ?>, this)" class="dl-btn danger-btn" style="width: 100%; font-size: 0.95rem; font-weight: bold; padding: 10px;"><?= __('Abandon Quest') ?></button>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <!-- Right Column: Leaderboard -->
        <aside class="sidebar delay-3">
            <!-- Instructions Widget -->
            <div class="leaderboard-widget">
                <h3 style="border-bottom-color: var(--pso-blue); color: var(--pso-blue);"><?= __('How to Play') ?></h3>
                <p>
                    <?= __('The Game Master automatically generates specially curated bounties tailored specifically to your character\'s stats and classes.') ?>
                    <br><br>
                    <?= __('Missions are automatically assigned to your characters as you play! You can hold up to 3 active bounties per character at a time. Check back regularly or log into the game to receive your next assignment from the Hunter\'s Guild!') ?>
                </p>
            </div>



            <!-- Global Top Leaderboard -->
            <div class="leaderboard-widget">
                <h3><?= __('Top Hunters') ?></h3>
                <?php if (empty($leaderboard)): ?>
                    <p style="text-align:center; opacity:0.6; padding: 1rem;"><?= __('The leaderboard is waiting for its first legend.') ?></p>
                <?php else: ?>
                    <ul class="leaderboard-list">
                        <?php foreach ($leaderboard as $idx => $lb): ?>
                            <?php $rank = $idx + 1; ?>
                            <li class="rank-<?= $rank ?>">
                                <div class="rank-wrapper">
                                    <div class="rank-badge"><?= $rank ?></div>
                                    <span class="player-name"><?= htmlspecialchars($lb['hunter_name']) ?></span>
                                </div>
                                <span class="completion-count"><?= number_format($lb['completions']) ?></span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <a href="/top_hunters.php" class="dl-btn" style="display:block; text-align:center; margin-top: 1rem; padding: 10px;"><?= __('View All Hunters') ?></a>
                <?php endif; ?>
            </div>
        </aside>

    </div>
</main>

<?php include 'includes/footer.php'; ?>

<!-- Drop Animation Overlay -->
<div id="drop-animation-overlay" class="drop-overlay" style="display: none;">
    <div id="countdown-text" class="countdown-text"></div>
    <div class="thank-you-text" id="thank-you-text"><?= __('BOUNTY CLAIMED!') ?></div>
    <div class="drop-item-box" id="drop-item-box">
        <div class="drop-box-core">
            <div class="face front"></div>
            <div class="face back"></div>
            <div class="face right"></div>
            <div class="face left"></div>
            <div class="face top"></div>
            <div class="face bottom"></div>
        </div>
        <div class="drop-box-glow"></div>
    </div>
</div>

<style>
/* Custom Drop Animation */
.drop-overlay {
    position: fixed;
    top: 0; left: 0; width: 100vw; height: 100vh;
    background: rgba(0, 0, 0, 0.9);
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    perspective: 1000px;
}
.drop-item-box {
    position: relative;
    width: 60px;
    height: 60px;
    transform-style: preserve-3d;
    animation: dropIn 1s cubic-bezier(0.25, 1, 0.5, 1) forwards;
}
.thank-you-text {
    position: absolute;
    top: 20%;
    width: 100%;
    text-align: center;
    font-family: 'Share Tech Mono', 'Segoe UI', monospace;
    font-size: 4rem;
    color: #fff;
    text-shadow: 0 0 20px rgba(0, 255, 255, 1), 0 0 40px rgba(0, 255, 255, 0.8);
    z-index: 10000;
    opacity: 0;
    pointer-events: none;
}
.countdown-text {
    position: absolute;
    top: 40%;
    width: 100%;
    text-align: center;
    font-family: 'Share Tech Mono', 'Segoe UI', monospace;
    font-size: 8rem;
    color: #fff;
    text-shadow: 0 0 30px rgba(255, 255, 255, 1);
    z-index: 10001;
    transition: transform 0.2s ease;
    pointer-events: none;
}

.drop-box-core {
    width: 100%;
    height: 100%;
    position: relative;
    transform-style: preserve-3d;
    transform: rotateX(-30deg) rotateY(45deg);
    animation: spinBox 3s linear infinite;
}
.drop-box-core .face {
    position: absolute;
    width: 60px;
    height: 60px;
    background: rgba(255, 42, 42, 0.8);
    border: 2px solid #ffaaaa;
    box-shadow: inset 0 0 15px rgba(255,255,255,0.5);
    backface-visibility: inherit;
}
.drop-box-core .face.front  { transform: rotateY(  0deg) translateZ(30px); }
.drop-box-core .face.right  { transform: rotateY( 90deg) translateZ(30px); }
.drop-box-core .face.back   { transform: rotateY(180deg) translateZ(30px); }
.drop-box-core .face.left   { transform: rotateY(-90deg) translateZ(30px); }
.drop-box-core .face.top    { transform: rotateX( 90deg) translateZ(30px); }
.drop-box-core .face.bottom { transform: rotateX(-90deg) translateZ(30px); }
.drop-box-glow {
    position: absolute;
    top: 50%; left: 50%;
    width: 200px; height: 200px;
    background: radial-gradient(circle, rgba(255, 42, 42, 0.8) 0%, transparent 70%);
    transform: translate(-50%, -50%);
    opacity: 0;
    animation: glowBurst 1.5s 0.8s forwards;
}

@keyframes dropIn {
    0% { transform: translateY(-300px) scale(0.5); opacity: 0; }
    60% { transform: translateY(20px) scale(1.1); opacity: 1; }
    80% { transform: translateY(-10px) scale(0.95); }
    100% { transform: translateY(0) scale(1); opacity: 1; }
}
@keyframes textDrop {
    0% { transform: translateY(-100px) scale(0.8); opacity: 0; }
    100% { transform: translateY(0) scale(1); opacity: 1; }
}
@keyframes spinBox {
    from { transform: rotateX(-20deg) rotateY(0deg); }
    to { transform: rotateX(-20deg) rotateY(360deg); }
}
@keyframes glowBurst {
    0% { opacity: 0; transform: translate(-50%, -50%) scale(0.5); }
    50% { opacity: 1; transform: translate(-50%, -50%) scale(1.2); }
    100% { opacity: 0; transform: translate(-50%, -50%) scale(2); }
}
</style>
