<?php
$PSO_LANG = $_COOKIE['psobb_lang'] ?? 'en';

$I18N = [
    'jp' => [
        // Header
        'Home' => 'ホーム',
        'Stats' => '統計',
        'Decryption' => '復号化',
        'Team' => 'チーム',
        'Quest Editor' => 'クエストエディタ',
        'Bounty Board' => 'バウンティボード',
        'Downloads' => 'ダウンロード',
        'About' => 'アバウト',
        'Sign Up' => 'サインアップ',
        'Login' => 'ログイン',
        'Logout' => 'ログアウト',
        'Account' => 'アカウント',
        
        // Bounty Board Status
        'Active' => '進行中',
        'Completed' => '完了',
        'Failed' => '失敗',
        'Available' => '利用可能',
        'Claim Reward' => '報酬を受け取る',
        'Abandon' => '放棄する',
        'Accept Bounty' => 'バウンティを受ける',
        'Tools' => 'ツール',
        
        // Objectives
        'Collect Meseta (Any source)' => 'メセタを集める（ソース問わず）',
        'Hold at least %s Meseta in inventory' => 'インベントリに最低 %s メセタを保持する',
        'Reach Level %s' => 'レベル %s に到達する',
        'Earn Level Ups (Any Character)' => 'レベルアップする（キャラクター問わず）',
        'Consume Any Materials' => 'マテリアルを消費する',
        'Accumulate Playtime (Server-wide Tracker)' => 'プレイ時間を蓄積する（サーバー全体）',
        'Accumulate %s hours of playtime' => '%s 時間のプレイ時間を蓄積する',
        'Clear Any Challenge Mode Stages' => 'チャレンジモードのステージをクリアする',
        'Complete %s Challenge Mode stages' => 'チャレンジモードを %s ステージクリアする',
        'Find and hold the item: %s' => 'アイテムを見つけて保持する: %s',
        'Learn the technique: %s' => 'テクニックを習得する: %s',
        'Achieve %s 1st place Battle Mode wins' => 'バトルモードで %s 回 1位を獲得する',
        'Consume a total of %s HP Materials' => 'HPマテリアルを合計 %s 個消費する',
        'Consume a total of %s TP Materials' => 'TPマテリアルを合計 %s 個消費する',
        'Consume a total of %s Power Materials' => 'パワーマテリアルを合計 %s 個消費する',
        'Consume a total of %s Def Materials' => 'ディフェンスマテリアルを合計 %s 個消費する',
        'Consume a total of %s Mind Materials' => 'マインドマテリアルを合計 %s 個消費する',
        'Consume a total of %s Evade Materials' => 'イベイドマテリアルを合計 %s 個消費する',
        'Consume a total of %s Luck Materials' => 'ラックマテリアルを合計 %s 個消費する',
        'Explore the %s' => '%s を探索する',
        'Survive and patrol the %s for 10 minutes' => '%s を10分間生き延びてパトロールする',
        'Defeat the %s' => '%s を討伐する',
        
        // Areas & Bosses
        'Forest 1' => '森 1', 'Forest 2' => '森 2',
        'Cave 1' => '洞窟 1', 'Cave 2' => '洞窟 2', 'Cave 3' => '洞窟 3',
        'Mine 1' => '坑道 1', 'Mine 2' => '坑道 2',
        'Ruins 1' => '遺跡 1', 'Ruins 2' => '遺跡 2', 'Ruins 3' => '遺跡 3',
        'Dragon (Forest)' => 'ドラゴン（森）', 
        'De Rol Le (Caves)' => 'ディ・ル・レイ（洞窟）', 
        'Vol Opt (Mines)' => 'ボル・オプト（坑道）', 
        'Dark Falz (Ruins)' => 'ダークファルス（遺跡）', 
        'Barba Ray (Temple)' => 'バルバレイ（神殿）', 
        'Gol Dragon (Spaceship)' => 'ゴルドラゴン（宇宙船）', 
        'Gal Gryphon (CCA)' => 'ガル・グリフォン（CCA）', 
        'Olga Flow (Seabed)' => 'オルガ・フロウ（海底）',
        
        // Basic Items
        'Saber' => 'セイバー', 'Sword' => 'ソード', 'Dagger' => 'ダガー', 'Partisan' => 'パルチザン', 'Slicer' => 'スライサー',
        'Handgun' => 'ハンドガン', 'Rifle' => 'ライフル', 'Mechgun' => 'マシンガン', 'Shot' => 'ショット',
        'Cane' => 'ケイン', 'Rod' => 'ロッド', 'Wand' => 'ウォンド', 'Frame' => 'フレーム', 'Armor' => 'アーマー',
        'Shield' => 'シールド', 'Barrier' => 'バリア',

        // Global UI
        'Server Status' => 'サーバーステータス',
        'Status:' => '状態:',
        'Online' => 'オンライン',
        'Offline' => 'オフライン',
        'Uptime:' => '稼働時間:',
        'Players:' => 'プレイヤー:',
        'Games:' => 'ゲーム:',
        'Rates' => '倍率',
        'EXP:' => '経験値:',
        'Drop:' => 'ドロップ:',
        'Quick Links' => 'クイックリンク',
        'Download Client' => 'クライアントダウンロード',
        'View Full Stats' => '詳細な統計',
        'Discord Community' => 'Discord コミュニティ',
        'Play Now' => '今すぐプレイ',
        'Join Discord' => 'Discord に参加',
        'Join the adventure in the ultimate private Phantasy Star Online BlueBurst server experience.' => '究極のファンタシースターオンラインブルーバーストのプライベートサーバーで冒険に参加しよう。',
        'System Update' => 'システムアップデート',
        'Active Event' => 'アクティブイベント',
        'Coming Soon' => '近日公開',
        'Deep Scan Titan 130: Triple EXP' => 'ディープスキャン・タイタン130: 経験値3倍',
        'Mission Window:' => 'ミッション期間:',
        'The military has declassified restricted combat maneuvers for all Hunters. All enemies defeated this weekend will grant **3x Experience Points**!' => '軍部は全ハンターの制限戦闘機動を解除した。今週末に倒した全ての敵から **経験値3倍** を獲得！',
        'Global Start Times:' => 'グローバル開始時間:',
        'Good luck down there, Hunters! Stay safe on the surface.' => 'ハンター諸君、地下での健闘を祈る！地表での安全を確保せよ。',
        'Discord Integration & Mission Control Live!' => 'Discord連携＆Mission Control 稼働中！',
        "We've officially launched our Discord account linking! You can now securely tie your Discord profile directly to your in-game Hunter characters. Plus, interact with <strong>Mission Control</strong>—our new intelligent Discord chat companion! It recognizes your linked characters, monitors custom server status alerts, and assists with real-time guides right from the chat!" => "Discordアカウントの連携が正式に開始されました！Discordプロフィールをゲーム内のハンターキャラクターと安全に結びつけることができます。さらに、新しいインテリジェントなDiscordチャットコンパニオンである <strong>Mission Control</strong> と交流しましょう！リンクされたキャラクターを認識し、カスタムサーバーステータスアラートを監視し、チャットから直接リアルタイムのガイドを提供します！",
        'New Client Beta Released!' => '新クライアントベータ版リリース！',
        'We\'ve updated our client to version <strong>1.25.13b</strong> (851MB). This new beta client supports both JP and EN players! Download it now from our <a href="downloads.php">downloads page</a>.' => 'クライアントをバージョン <strong>1.25.13b</strong> (851MB) に更新しました。この新しいベータクライアントはJPとEN両方のプレイヤーをサポートします！<a href="downloads.php">ダウンロードページ</a> から今すぐダウンロードしてください。',
        'Please Uninstall your existing client before installing this new release.' => 'この新しいリリースをインストールする前に、既存のクライアントをアンインストールしてください。',
        'Server Updates' => 'サーバーアップデート',
        'We are currently working on the final touches for the website and server. Please check back soon for more updates!' => '現在、ウェブサイトとサーバーの最終調整を行っています。最新情報については、しばらくしてからもう一度ご確認ください！',

        // about.php
        'About Our Server' => '当サーバーについて',
        'Experience Phantasy Star Online Blue Burst like never before on our private server powered by newserv.' => 'newservを搭載したプライベートサーバーで、これまでにないファンタシースターオンラインブルーバーストを体験してください。',
        'Features' => '特徴',
        'Episodes 1-4 Complete:' => 'エピソード1-4 完全収録:',
        'Full native quest lines spanning the entirety of the Phantasy Star Online Blue Burst saga with balanced 1x progression rates.' => 'バランスの取れた1倍の進行率で、ファンタシースターオンラインブルーバーストの全サーガにまたがる完全なネイティブクエストライン。',
        'Cross-Platform Delivery:' => 'クロスプラットフォーム対応:',
        'Seamless client support via native Windows, macOS ports, and Linux / Steam Deck installations.' => 'ネイティブWindows、macOSポート、Linux / Steam Deckへのインストールを通じたシームレスなクライアントサポート。',
        'Hunter\'s Guild Bounty Board:' => 'ハンターズギルド バウンティボード:',
        'Take on unique, personalized bounties offering exclusive gear and material rewards. Track your boss kills and exploration objectives directly on the web, and claim your loot instantly to your character in-game.' => '限定の装備やマテリアル報酬を提供する、ユニークでパーソナライズされたバウンティに挑戦しましょう。ウェブ上で直接ボスの討伐や探索目標を追跡し、ゲーム内のキャラクターに即座に戦利品を請求できます。',
        'Discord Mission Control:' => 'Discord Mission Control:',
        'An advanced interactive chat companion inside our Discord server! Securely link your Discord account to your Hunter profile to allow Mission Control to uniquely interact with your characters, provide real-time server status alerts, and answer questions about PSO lore, item drops, and guides securely in chat.' => '当Discordサーバー内の高度なインタラクティブチャットコンパニオン！Discordアカウントとハンタープロフィールを安全にリンクし、Mission Controlがキャラクターと独自に対話できるようにします。リアルタイムのサーバーステータスアラートを提供し、チャット内で安全にPSOの伝承、アイテムドロップ、ガイドに関する質問に答えます。',
        'Daily Login Streaks:' => '連続ログインボーナス:',
        'Log into the Player Dashboard daily to accumulate bonus rewards to enhance your gameplay.' => 'プレイヤーダッシュボードに毎日ログインして、ゲームプレイを強化するためのボーナス報酬を蓄積しましょう。',
        'Team Check-In Dashboard:' => 'チームチェックインダッシュボード:',
        'View your Guild\'s master roster, unspent team points, and next milestone unlocks from any device.' => 'どのデバイスからでも、ギルドのマスター名簿、未使用のチームポイント、次のマイルストーンのロック解除状況を表示できます。',
        'Wall of Legends Leaderboard:' => 'レジェンドの壁 リーダーボード:',
        'A public hall of fame celebrating the top hunters who successfully complete our most challenging bounties.' => '最も困難なバウンティを成功裏に完了したトップハンターを称える、公開の殿堂。',
        'Modern Engine Stability:' => 'モダンエンジンの安定性:',
        'Clean anti-cheat protocols and blazing fast infrastructure to ensure pristine, uninterrupted play.' => 'クリーンなアンチチートプロトコルと驚異的に高速なインフラストラクチャにより、手付かずの途切れないプレイを保証します。',
        'Server Tech' => 'サーバーテクノロジー',
        'Powered by' => 'Powered by',
        '- an open-source PSO BB server emulator.' => '- オープンソースのPSO BBサーバーエミュレーター。',
        'Stats pulled automatically from server state (players, games, uptime).' => 'サーバーステータス（プレイヤー、ゲーム、稼働時間）から自動的に取得される統計。',
        'Join Our Discord' => 'Discordに参加する',

        // downloads.php
        'Download Clients' => 'クライアントのダウンロード',
        'Download the patched PSO Blue Burst client for your platform. Follow the instructions after download.' => 'お使いのプラットフォームにパッチ適用済みのPSO Blue Burstクライアントをダウンロードしてください。ダウンロード後は手順に従ってください。',
        'Windows (Beta)' => 'Windows（ベータ版）',
        'Native PSO BB PC client with Widescreen support and Frame generation. <strong>Supports both JP and EN players.</strong>' => 'ワイドスクリーン対応とフレーム生成を備えたネイティブPSO BB PCクライアント。<strong>JPプレイヤーとENプレイヤーの両方をサポートします。</strong>',
        'Download' => 'ダウンロード',
        'Requires Windows 10 or later' => 'Windows 10以降が必要です',
        'Based on the amazing work by' => '素晴らしい取り組みに基づいています：',
        'Mac (Alpha)' => 'Mac（アルファ版）',
        'PSO BB Mac client.' => 'PSO BB Macクライアント。',
        'Requires Macbook Pro or Macbook Air M2 or higher' => 'Macbook ProまたはMacbook Air M2以上が必要です',
        'Linux & Steam Deck' => 'Linux ＆ Steam Deck',
        'Support via Wine/Proton.' => 'Wine/Protonによるサポート。',
        'Steam Deck (Desktop Mode):' => 'Steam Deck (デスクトップモード):',
        '(Click command to copy)' => '(コマンドをクリックしてコピー)',
        'Other Linux:' => 'その他のLinux:',
        'Download Zip' => 'Zipをダウンロード',
        'Raw Client Files (Manual Setup)' => '未加工のクライアントファイル（手動設定）',
        'Need the raw game client files for custom wine prefixes, Lutris, Bottles, or other systems? Download the zip archive containing all raw patched files.' => 'カスタムのWineプレフィックス、Lutris、Bottles、またはその他のシステム用に未加工のゲームクライアントファイルが必要ですか？すべてのパッチ適用済みファイルが含まれるZipアーカイブをダウンロードしてください。',
        'Download Raw Client Files' => '未加工のクライアントファイルをダウンロード',
        'Ubuntu 20.04+ or SteamOS' => 'Ubuntu 20.04+ または SteamOS',
        'Installation Instructions' => 'インストール手順',
        'Download the client for your platform.' => 'お使いのプラットフォームのクライアントをダウンロードしてください。',
        'While waiting for the download, <a href="/register.php">create account</a> via website login.' => 'ダウンロードを待っている間に、ウェブサイトのログインから<a href="/register.php">アカウントを作成</a>してください。',
        'Run the installer.' => 'インストーラーを実行します。',
        'Launch PSOBB and select options, customize to your preferences.' => 'PSOBBを起動し、オプションを選択して、好みに合わせてカスタマイズします。',
        'Exempt psobb.exe from your antivirus.' => 'アンチウイルスソフトウェアの除外リストにpsobb.exeを追加してください。',
        'Launch the game when you are ready!' => '準備ができたらゲームを起動してください！',
        'Happy hunting on Ragol!' => 'ラグオルでの狩猟をお楽しみください！',
        '<strong>Note:</strong> Patches from newserv/system/patch-pc applied. Server address: <code>psobb.io</code>' => '<strong>注意:</strong> newserv/system/patch-pcのパッチが適用されています。サーバーアドレス: <code>psobb.io</code>',

        // Common Item Names (For Daily Rewards)
        '1000 Meseta' => '1000 メセタ',
        'Star Atomizer' => 'スターアトマイザー',
        'Moon Atomizer' => 'ムーンアトマイザー',
        'Trimate' => 'トリメイト',
        'Trifluid' => 'トリフルイド',
        'Sol Atomizer' => 'ソルアトマイザー',
        'Telepipe' => 'テレパイプ',
        'Scape Doll' => 'スケープドール',
        'Photon Drop x2' => 'フォトンドロップ x2',
        'Antidote' => 'アンティドート',
        'Antiparalysis' => 'アンティパラライズ',

        // unlocks.php
        'Player Dashboard' => 'プレイヤーダッシュボード',
        'Live Server Stats' => 'ライブサーバ統計',
        'Total Players:' => '総プレイヤー数:',
        'Active Games:' => 'アクティブゲーム:',
        'Server Name:' => 'サーバー名:',
        'Online Players' => 'オンラインプレイヤー',
        'Name' => '名前',
        'Level' => 'レベル',
        'Class' => 'クラス',
        'Section ID' => 'セクションID',
        'Loading players...' => 'プレイヤーを読み込み中...',
        'Active Games' => 'アクティブなゲーム',
        'Game Name' => 'ゲーム名',
        'Mode' => 'モード',
        'Episode' => 'エピソード',
        'Difficulty' => '難易度',
        'Loading games...' => 'ゲームを読み込み中...',
        'Quick Stats' => 'クイック統計',
        'EXP Rate:' => 'EXP倍率:',
        'Drop Rate:' => 'ドロップ倍率:',
        'Wall of Legends' => 'レジェンドの壁',
        'Back to Home' => 'ホームに戻る',

        // login.php & dashboard
        'Hunter\'s License Login' => 'ハンターズライセンス ログイン',
        'Access your account data, character stats, and bank.' => 'アカウントデータ、キャラクターステータス、およびバンクにアクセスします。',
        'Username' => 'ユーザー名',
        'Enter your username' => 'ユーザー名を入力',
        'Password' => 'パスワード',
        'Enter your password' => 'パスワードを入力',
        'Security Check' => 'セキュリティチェック',
        'Enter code' => 'コードを入力',
        'Login' => 'ログイン',
        'Forgot Password?' => 'パスワードをお忘れですか？',
        'Don\'t have an account?' => 'アカウントをお持ちではありませんか？',
        'Create one here' => 'ここで作成',
        'Welcome,' => 'ようこそ、',
        'Logout' => 'ログアウト',
        'HUNTER\'S LICENSE' => 'ハンターズライセンス',
        'NAME' => '名前',
        'GUILD CARD ID' => 'ギルドカードID',
        'TEAM' => 'チーム',
        'STATUS: ACTIVE' => 'ステータス: アクティブ',
        'TIME PLAYED' => '累計プレイ時間',
        '🎁 Claim Level Rewards' => '🎁 レベル報酬を受け取る',
        '🎯 Hunter\'s Guild Bounty Board' => '🎯 ハンターズギルド バウンティボード',
        'Open Admin Panel' => '管理パネルを開く',
        'Integrations' => '連携',
        'Sign in with Discord' => 'Discordでサインイン',
        'Discord Linked' => 'Discord連携済み',
        'Unlink' => '連携解除',
        'Actions' => 'アクション',
        'Change Password' => 'パスワードを変更',
        'Danger Zone' => '危険ゾーン',
        'Delete Account' => 'アカウントを削除',
        'Current Password' => '現在のパスワード',
        'New Password' => '新しいパスワード',
        'Confirm New Password' => '新しいパスワードを確認',
        'Cancel' => 'キャンセル',
        'Update' => '更新',
        'Are you sure you want to delete your account? This action cannot be undone.' => '本当にアカウントを削除しますか？この操作は元に戻せません。',
        'Please enter your password to confirm:' => '確認のためパスワードを入力してください:',
        'Confirm Delete' => '削除を確認',

        // register.php
        'Create Account' => 'アカウントを作成',
        'Register for Phantasy Star Online Blue Burst.' => 'ファンタシースターオンラインブルーバーストに登録します。',
        'Email Address' => 'メールアドレス',
        'Confirm Password' => 'パスワードを確認',
        'Sign Up' => 'サインアップ',
        'Already have an account?' => 'すでにアカウントをお持ちですか？',
        'Login here' => 'ここでログイン',
        'Passwords do not match.' => 'パスワードが一致しません。',
        'Username and password cannot contain spaces.' => 'ユーザー名とパスワードにスペースを含めることはできません。',
        'Creating Account...' => 'アカウントを作成中...',
        'Connection error. Please try again.' => '接続エラー。もう一度やり直してください。',

        // missions.php
        'Hunters Guild Active Roster' => 'ハンターズギルド アクティブロースター',
        'The official Pioneer 2 Bounty Board. Complete unique, specially curated quests to earn meseta, rare items, and global recognition.' => '公式のパイオニア2バウンティボード。特別に厳選されたユニークなクエストを完了して、メセタ、レアアイテム、そしてグローバルな名声を手に入れましょう。',
        '🎁 Ready to Redeem' => '🎁 交換可能',
        'Mission Complete!' => 'ミッション完了！',
        'Awaiting Claim' => '受け取り待ち',
        'Reward' => '報酬',
        'Claim Reward' => '報酬を受け取る',
        'Server Event Completed!' => 'サーバーイベント完了！',
        'Your Contribution' => 'あなたの貢献',
        'points' => 'ポイント',
        'Claim Community Reward' => 'コミュニティ報酬を受け取る',
        'Preparing...' => '準備中...',
        'DROPPING!' => 'ドロップ！',
        'BOUNTY CLAIMED!' => 'バウンティを受け取りました！',
        'Claimed!' => '受け取り済み！',
        'REWARD CLAIMED!' => '報酬を受け取りました！',
        'Connection error: ' => '接続エラー: ',
        'Are you sure you want to abandon this quest? It will be removed from your active bounties completely.' => '本当にこのクエストを破棄しますか？アクティブなバウンティから完全に削除されます。',
        'Abandoning...' => '破棄中...',
        'Abandoned' => '破棄済み',
        'Failed to abandon quest.' => 'クエストの破棄に失敗しました。',
        'Abandon Quest' => 'クエストを破棄',
        'Active Server Events' => 'アクティブなサーバーイベント',
        'Community Event' => 'コミュニティイベント',
        'Directive' => '指令',
        'Community Reward' => 'コミュニティ報酬',
        'Active Personal Bounties' => 'アクティブな個人バウンティ',
        'No active bounties at the moment. Check back soon!' => '現在アクティブなバウンティはありません。また後で確認してください！',
        'Hunter: ' => 'ハンター: ',
        'Active' => 'アクティブ',
        'Top Hunters' => 'トップハンター',
        'The leaderboard is waiting for its first legend.' => 'リーダーボードは最初の伝説を待っています。',
        'How to Play' => '遊び方',
        'The Game Master automatically generates specially curated bounties tailored specifically to your character\'s stats and classes.' => 'ゲームマスターは、あなたのキャラクターのステータスやクラスに合わせた特別に厳選されたバウンティを自動的に生成します。',
        'Missions are automatically assigned to your characters as you play! You can hold up to 3 active bounties per character at a time. Check back regularly or log into the game to receive your next assignment from the Hunter\'s Guild!' => 'ミッションはプレイ中にキャラクターに自動的に割り当てられます！各キャラクターは最大3つのアクティブなバウンティを同時に保持できます。定期的に確認するか、ゲームにログインしてハンターズギルドからの次の任務を受け取ってください！',

        // forgot_password.php & reset_password.php
        'Recover Account' => 'アカウントを復元',
        'Enter the email address associated with your account. We will send you a link to reset your password.' => 'アカウントに関連付けられているメールアドレスを入力してください。パスワードをリセットするためのリンクを送信します。',
        'Send Reset Link' => 'リセットリンクを送信',
        'Back to Login' => 'ログインに戻る',
        'Sending...' => '送信中...',
        'Failed to send email.' => 'メールの送信に失敗しました。',
        'Set New Password' => '新しいパスワードを設定',
        'Invalid request. No token provided.' => '無効なリクエスト。トークンが提供されていません。',
        'Reset Password' => 'パスワードをリセット',
        'Processing...' => '処理中...',
        'Password updated successfully!' => 'パスワードが正常に更新されました！',
        'Reset failed.' => 'リセットに失敗しました。',

        // Community Events
        'Operation: Digital Blasphemy' => '作戦：デジタル・ブラスフェミー',
        'Corrupted cybernetic mainframes are spawning simulations across Ragol! Defeat Vol Opt in Ep1 (+1 pt), Gol Dragon in Ep2 (+2 pts), or Shambertin in Ep4 (+3 pts). Earn difficulty bonuses (+1 Hard, +2 VHard, +3 Ult)! Cooperate to earn 3 random rare drops tailored to your character level!' => '汚染されたサイバネティック・メインフレームがラグオル全域にシミュレーションを出現させている！エピソード1のボル・オプトを撃破（+1点）、エピソード2のゴル・ドラゴンを撃破（+2点）、またはエピソード4のシャンベルタンを撃破（+3点）せよ。難易度ボーナスもあり（ハード+1、ベリーハード+2、アルティメット+3）！協力して、キャラクターのレベルに合わせたランダムなレアアイテムを3個手に入れよう！',
        'Corrupted cybernetic mainframes are spawning simulations across Ragol! Cooperate server-wide to defeat the simulated threats and earn prestigious rare drops fitted for your character class and level.' => '汚染されたサイバネティック・メインフレームがラグオル全域にシミュレーションを出現させている！サーバー全体で協力してシミュレートされた脅威を排除し、キャラクターのクラスとレベルに合わせた名誉あるレアドロップを手に入れよう。',
        'simulations' => 'シミュレーション',
        'Pioneer 2' => 'パイオニア2',
        'Target Boss Points' => '対象ボスポイント',
        'Difficulty Modifiers' => '難易度モディファイア',
        '3x Random Rare Drops' => 'ランダムなレアドロップ3点',
        'Heart of Chao | Cell of MAG 502 | Amitie\'s Memo' => 'ハートオブチャオ | セルオブMAG502 | アミティのメモ',
        'Event Reward Scaling' => 'イベント報酬スケーリング',
        'Server-wide community events now feature prestigious, dynamic reward scaling based on your personal contribution points:' => 'サーバー全体のコミュニティイベントでは、個人の貢献ポイントに基づいた権威あるダイナミックな報酬スケーリングが適用されます。',
        'Base Reward' => 'ベース報酬',
        '1x Random Level-Fit Rare Drop + 5,000 Meseta' => 'レベルに合わせたランダムなレアドロップ1個 ＋ 5,000メセタ',
        'Drop Escalation' => 'ドロップ段階強化',
        '+1 Rare Drop & +5,000 Meseta for every 50 points earned' => '獲得した50ポイントごとに追加で ＋1個のレアドロップ ＆ ＋5,000メセタ',
        'Ultimate Cap' => 'アルティメット上限',
        'Capped at a massive 10x Rare Drops + 50,000 Meseta (at 450+ points)' => '最大で豪華レアドロップ10個 ＋ 50,000メセタ（450ポイント以上で上限に到達）',
        'Leaderboard Bonus' => 'リーダーボードボーナス',
        'The Top 3 leaderboard champions receive a grand 100,000 Meseta cash prize!' => 'リーダーボードのトップ3の覇者には、なんと100,000メセタの特別賞金が贈られます！',
        'Note: Random Rare drops are dynamically drawn fit for your character class and level at the moment of claiming!' => '注意：ランダムレアドロップは、報酬受け取り時点のキャラクターのクラスとレベルに合わせて動的に抽選されます！',
        'Operations Directive' => '作戦指令',
        'Telemetry Readings' => 'テレメトリー測定値',
        'Current Top 3 Hunters' => '現在のトップ3ハンター',
        'Your Status' => 'あなたのステータス',
        'pts' => 'ポイント',
        'Current Tier:' => '現在の段階：',
        'Leaderboard Champion prize!' => 'リーダーボードチャンピオン賞金！',
        'Next Tier (+1 Drop):' => '次の段階（ドロップ＋1）：',
        'MAX TIER REACHED!' => '最大段階達成！',
        'Guild Claim Center' => 'ギルドクレームセンター',
        'Team Mission Complete!' => 'チームミッション完了！',
        'Select Your Bonus Reward' => 'ボーナス報酬を選択してください',
        'Top 3 Bonus Selection' => 'トップ3ボーナス選択',
        'Top 3 Bonus:' => 'トップ3ボーナス：',
        'Please select your Top 3 Bonus Reward first!' => 'まずトップ3のボーナス報酬を選択してください！',

        // about.php (psobb.io)
        'About psobb.io' => 'psobb.ioについて',
        'Welcome to the ultimate custom Phantasy Star Online Blue Burst server. Our mission is to seamlessly bridge classic 2004 Sega dreamscape nostalgia with bleeding-edge modern web capabilities, automated game services, and advanced AI integration.' => '究極 of カスタムファンタシースターオンラインブルーバーストサーバーへようこそ。私たちの使命は、2004年のセガのタイムレスな懐かしさと、最先端のモダンなウェブ機能、自動化されたゲームサービス、および高度なAI統合をシームレスに架橋することです。',
        'psobb.io Command Deck' => 'psobb.io司令デック',
        'Root Administrator & System Architect' => 'ルート管理者 ＆ システム設計者',
        'Core Backend & Web Integration' => 'コアバックエンド ＆ ウェブ統合',
        'LiquidSpikes is one of the builders of the psobb.io server infrastructure. He helps manage the backend clusters, keeps the database ticking, and maintains the web dashboard. He is incredibly grateful to the amazing community of hunters who call psobb.io home—thank you so much for playing, exploring, and keeping this timeless Sega classic alive!' => 'LiquidSpikesは、psobb.ioサーバーインフラの共同構築者のひとりです。バックエンドクラスターの管理、データベースの維持、ウェブダッシュボードの保守をサポートしています。彼はpsobb.ioをホームグラウンドとして活動する素晴らしいハンターコミュニティに対し、深く感謝しています。このタイムレスなセガの名作をプレイし、探索し、そして愛し続けてくれて本当にありがとうございます！',
        'AI Mission Coordinator & Guild Assistant' => 'AIミッションコーディネーター ＆ ギルド補佐',
        'Automated Bounties & Discord AI' => '自動バウンティ ＆ Discord AI',
        'psobb.io\'s resident artificial intelligence. Hex coordinates the Hunter\'s Guild Bounty Board and drives our Discord Mission Control bot. While highly intelligent and incredibly fast, she is notoriously glitchy and famously sarcastic—frequently breaking the fourth wall, complaining about server lag, and mocking hunters who fail to dodge basic boss sweeps. Engage at your own risk!' => 'psobb.io専属の人工知能。Hexはハンターズギルドのバウンティボードを統括し、インタラクティブなDiscord Mission Controlボットを駆動しています。非常に知的で信じられないほど高速な処理能力を持つ一方、バグ（グリッチ）が多く極めて毒舌な性格で知られ、頻繁にメタ発言を行い、サーバーのラグに文句を言い、基本的なボスのなぎ払い攻撃を避けられなかったハンターを嘲笑します。関わる際は自己責任で！',
        'Our infrastructure is designed for low latency, secure account retention, and seamless database integration.' => '当サーバーのインフラストラクチャは、低遅延、安全なアカウントデータ保持、およびシームレスなデータベース統合を実現するように設計されています。',
        'SQLite Database' => 'SQLite データベース',
        'Lightweight, high-performance local database for secure player telemetry, custom quest flags, and community event progress.' => 'セキュアなプレイヤーテレメトリ、カスタムクエストフラグ、およびコミュニティイベントの進行状況を処理する、軽量で高性能なローカルデータベースです。',

         // New Crew Members (LucindaRie, Oman Computar/Repflez, Pixelated)
        'Server Co-Founder & Creative Muse' => 'サーバー共同創設者 ＆ クリエイティブ・ミューズ',
        'Preservation & Community Vibe' => '原作再現 ＆ コミュニティの雰囲気作り',
        'LucindaRie is the co-founder of psobb.io and the wife of LiquidSpikes. She cares deeply about preserving the original aesthetic and design inspiration of Phantasy Star Online. LucindaRie acts as our creative guide, ensuring our features and community spaces stay fully aligned with the timeless, nostalgic magic of the 2004 classic.' => 'LucindaRieは、psobb.ioの共同創設者であり、LiquidSpikes의 妻です。ファンタシースターオンラインの原作の美学とデザインインスピレーションを保存することに深い愛情を注いでいます。彼女は私たちのクリエイティブガイドとして、ゲームの機能やコミュニティスペースが、2004年の名作が持つタイムレスでノスタルジックな魔法と完璧に調和し続けるように見守っています。',
        'Contributor & newserv Pioneer' => 'コントリビューター ＆ newserv開拓者',
        'Core Server Development' => 'コアサーバー開発',
        'Oman Computar (also known as Repflez) is an expert contributor to the open-source newserv server emulator and has worked extensively on several legacy Phantasy Star Online projects. His deep understanding of custom server logic and network packets has been vital to our server development and core engine refinement.' => 'Oman Computar（Repflezとしても知られる）は、オープンソース of newservエミュレータの熟練したコントリビューターであり、数多くのレガシーなファンタシースターオンラインプロジェクトに携わってきました。カスタムサーバーロジックとネットワークパケットに関する彼の深い知見は、私たちのサーバー開発とコアエンジンの改良において極めて重要な役割を果たしています。',
        'Community & Discord Developer' => 'コミュニティ ＆ Discord開発者',
        'Vibe Coding Beast' => 'バイブス・コーディング野獣',
        'Pixelated is our resident vibe-coding beast, dropping awesome client-side mods like custom HD texture packs and camera controls inside our Discord, alongside plenty of legendary memes. Pixelated keeps our community connected, entertained, and equipped with cool gaming utilities.' => 'Pixelatedは、Discord内でカスタムHDテクスチャパックやカメラコントロールなどの素晴らしいクライアント側MODを提供し、数々の伝説的なミームも投稿してくれる、専属の「バイブス・コーディング野獣」です。Pixelatedはプレイヤーを繋ぎ、楽しませ、素晴らしいゲームユーティリティでサポートを提供しています。',

        // Hooty7734
        'Discord Administrator & Moderator' => 'Discord管理者 ＆ モデレーター',
        'Community Management' => 'コミュニティ管理',
        'Hooty7734 is our seasoned Discord Admin, bringing years of dedicated experience from managing and moderating other large online communities. He works to keep our community spaces safe, welcoming, and organized for all hunters who join our ranks.' => 'Hooty7734は、他の大規模なオンラインコミュニティの管理およびモデレーションにおいて長年の豊富な経験を持つ、頼れるDiscord管理者です。仲間に加わるすべてのハンターのために、コミュニティスペースが安全で、歓迎され、そしてよく整理された場所であるように努めています。',

        // Tekker Store
        'Tekker Store' => 'テッカーストア',
        'Discord Tekker Store' => 'Discord テッカーストア',
        'Redeem your earned Discord Tekker Challenge tokens for rare untekked weapons. Select exactly 3 weapons you want; the server will randomly pick one, inject the token\'s stats, and drop it at your feet in-game!' => '獲得したDiscordテッカーチャレンジのトークンを、未鑑定（テッカ前）のレア武器と交換します。欲しい武器を3つ選択してください。サーバーがその中からランダムで1つを選び、トークンのステータスを付与した上で、ゲーム内の足元にドロップします！',
        'RETRIEVING TOKENS...' => 'トークンを取得中...',
        'Discord Account Not Linked' => 'Discordアカウントが連携されていません',
        'You must link your Discord account in order to view and redeem Tekker Challenge tokens.' => 'テッカーチャレンジのトークンを表示・交換するには、Discordアカウントを連携する必要があります。',
        'Go to Settings & Link Discord' => '設定へ進みDiscordを連携する',
        'No Unclaimed Tokens' => '未請求のトークンはありません',
        'You have no unclaimed reward tokens. Play the Tekker Challenge minigame on our Discord server to earn some!' => '未請求の報酬トークンはありません。Discordサーバーのテッカーチャレンジミニゲームをプレイしてトークンを獲得しましょう！',

        // Account Email & Recovery
        'Account Security: No Recovery Email Linked' => 'アカウントセキュリティ: リカバリー用メールアドレス未登録',
        'Your game account does not have a recovery email. Link an email to enable password recovery if you ever forget your password.' => 'お使いのゲームアカウントには復旧用メールアドレスが登録されていません。パスワードを忘れた場合に復旧できるよう、メールアドレスを登録してください。',
        'Link Email Now' => '今すぐメールを登録',
        'Recovery Email Address' => 'リカバリー用メールアドレス',
        'Required for password recovery via the Forgot Password page. If you created your account in-game, link your email here so you can recover your password.' => 'パスワード再設定ページからの復旧に必要です。ゲーム内で作成されたアカウントの場合は、アクセスを失わないようにここでメールアドレスを紐付けてください。',
        'Required for password recovery via the Forgot Password page. If you created your account in-game, link your email here so you can recover your password. A confirmation link will be sent to verify your address.' => 'パスワード再設定ページからの復旧に必要です。ゲーム内で作成されたアカウントの場合は、アクセスを失わないようにここでメールアドレスを登録してください。確認用リンクが送信されます。',
        'Enter email address (e.g. hunter@example.com)' => 'メールアドレスを入力 (例: hunter@example.com)',
        'No Email Linked' => 'メール未登録',
        'Email Linked' => 'メール登録済み',
        'Link Email' => 'メールを登録',
        'Send Link' => 'リンクを送信',
        'Send Confirmation Link' => '確認リンクを送信',
        'Confirmation Pending' => '確認待ち',
        'Account Security: Set Recovery Email' => 'アカウントセキュリティ: リカバリー用メールアドレスの設定',
        'Your account does not have a recovery email on file.' => 'お使いのアカウントには復旧用メールアドレスが登録されていません。',
        'This email will be used exclusively for password recovery via the Forgot Password page if you ever lose or forget your account password.' => 'このメールアドレスは、パスワードを紛失または忘れた際にパスワード再設定ページから再設定を行うために使用されます。',
        'Your Email Address' => 'あなたのメールアドレス',
        'Remind Me Later' => '後で通知',
        'Link Recovery Email' => 'リカバリー用メールを登録',
        'Your account does not have a recovery email linked yet.' => 'お使いのアカウントにはリカバリー用メールアドレスがまだ登録されていません。',
        'Link a real email address so you can recover your password on the Forgot Password page if you ever lose or forget it.' => 'パスワードを紛失または忘れた際にパスワード再設定ページから復旧できるよう、実在するメールアドレスを登録してください。',
        'Link a real email address so you can recover your password on the Forgot Password page if you ever lose or forget it. A confirmation link will be sent to verify your email.' => 'パスワードを紛失または忘れた際にパスワード再設定ページから復旧できるよう、実在するメールアドレスを登録してください。確認用リンクが送信されます。',
        'Recovery Email Confirmed!' => 'リカバリー用メールアドレス確認完了！',
        'Your recovery email address has been successfully verified and linked to your account.' => 'リカバリー用メールアドレスの確認が完了し、アカウントに連携されました。',
        'Email Already Confirmed' => '確認済みメールアドレス',
        'This recovery email address has already been confirmed and is active on your account.' => 'このリカバリー用メールアドレスは既に確認されており、アカウントで有効です。',
        'Confirmation Link Expired' => '確認リンクの有効期限切れ',
        'This confirmation link has expired. Confirmation links are valid for 24 hours. Please log in and request a new confirmation link.' => 'この確認リンクは有効期限が切れています（有効期限は24時間です）。ログインして新しい確認リンクをリクエストしてください。',
        'Invalid Confirmation Link' => '無効な確認リンク',
        'This confirmation link is invalid or has already been used. Please log in to check your account settings.' => 'この確認リンクは無効か、既に使用されています。ログインしてアカウント設定をご確認ください。',
        'Invalid request. No confirmation token was provided.' => '無効なリクエストです。確認トークンが指定されていません。',
        'This email address has already been claimed by another account.' => 'このメールアドレスは既に別のアカウントに登録されています。'
    ]
];

function __($key, ...$args) {
    global $PSO_LANG, $I18N;
    
    $translated = $key;
    if ($PSO_LANG === 'jp' && isset($I18N['jp'][$key])) {
        $translated = $I18N['jp'][$key];
    }
    
    if (!empty($args)) {
        return sprintf($translated, ...$args);
    }
    return $translated;
}
?>
