<?php
$PSO_LANG = $_COOKIE['psobb_lang'] ?? 'en';

$I18N = [
    'jp' => [
        // Header
        'Home' => 'ホーム',
        'Stats' => '統計',
        'Decryption' => '復号化',
        'Team' => 'チーム',
        'Quest Editor' => 'クエストエディタ',
        'Bounty Board' => 'バウンティボード',
        'Downloads' => 'ダウンロード',
        'About' => 'アバウト',
        'Sign Up' => 'サインアップ',
        'Login' => 'ログイン',
        'Logout' => 'ログアウト',
        'Account' => 'アカウント',
        
        // Bounty Board Status
        'Active' => '進行中',
        'Completed' => '完了',
        'Failed' => '失敗',
        'Available' => '利用可能',
        'Claim Reward' => '報酬を受け取る',
        'Abandon' => '放棄する',
        'Accept Bounty' => 'バウンティを受ける',
        'Tools' => 'ツール',
        
        // Objectives
        'Collect Meseta (Any source)' => 'メセタを集める（ソース問わず）',
        'Hold at least %s Meseta in inventory' => 'インベントリに最低 %s メセタを保持する',
        'Reach Level %s' => 'レベル %s に到達する',
        'Earn Level Ups (Any Character)' => 'レベルアップする（キャラクター問わず）',
        'Consume Any Materials' => 'マテリアルを消費する',
        'Accumulate Playtime (Server-wide Tracker)' => 'プレイ時間を蓄積する（サーバー全体）',
        'Accumulate %s hours of playtime' => '%s 時間のプレイ時間を蓄積する',
        'Clear Any Challenge Mode Stages' => 'チャレンジモードのステージをクリアする',
        'Complete %s Challenge Mode stages' => 'チャレンジモードを %s ステージクリアする',
        'Find and hold the item: %s' => 'アイテムを見つけて保持する: %s',
        'Learn the technique: %s' => 'テクニックを習得する: %s',
        'Achieve %s 1st place Battle Mode wins' => 'バトルモードで %s 回 1位を獲得する',
        'Consume a total of %s HP Materials' => 'HPマテリアルを合計 %s 個消費する',
        'Consume a total of %s TP Materials' => 'TPマテリアルを合計 %s 個消費する',
        'Consume a total of %s Power Materials' => 'パワーマテリアルを合計 %s 個消費する',
        'Consume a total of %s Def Materials' => 'ディフェンスマテリアルを合計 %s 個消費する',
        'Consume a total of %s Mind Materials' => 'マインドマテリアルを合計 %s 個消費する',
        'Consume a total of %s Evade Materials' => 'イベイドマテリアルを合計 %s 個消費する',
        'Consume a total of %s Luck Materials' => 'ラックマテリアルを合計 %s 個消費する',
        'Explore the %s' => '%s を探索する',
        'Survive and patrol the %s for 10 minutes' => '%s を10分間生き延びてパトロールする',
        'Defeat the %s' => '%s を討伐する',
        
        // Areas & Bosses
        'Forest 1' => '森 1', 'Forest 2' => '森 2',
        'Cave 1' => '洞窟 1', 'Cave 2' => '洞窟 2', 'Cave 3' => '洞窟 3',
        'Mine 1' => '坑道 1', 'Mine 2' => '坑道 2',
        'Ruins 1' => '遺跡 1', 'Ruins 2' => '遺跡 2', 'Ruins 3' => '遺跡 3',
        'Dragon (Forest)' => 'ドラゴン（森）', 
        'De Rol Le (Caves)' => 'ディ・ル・レイ（洞窟）', 
        'Vol Opt (Mines)' => 'ボル・オプト（坑道）', 
        'Dark Falz (Ruins)' => 'ダークファルス（遺跡）', 
        'Barba Ray (Temple)' => 'バルバレイ（神殿）', 
        'Gol Dragon (Spaceship)' => 'ゴルドラゴン（宇宙船）', 
        'Gal Gryphon (CCA)' => 'ガル・グリフォン（CCA）', 
        'Olga Flow (Seabed)' => 'オルガ・フロウ（海底）',
        
        // Basic Items
        'Guilty Light' => 'ギルティライト',
        'Saber' => 'セイバー', 'Sword' => 'ソード', 'Dagger' => 'ダガー', 'Partisan' => 'パルチザン', 'Slicer' => 'スライサー',
        'Handgun' => 'ハンドガン', 'Rifle' => 'ライフル', 'Mechgun' => 'マシンガン', 'Shot' => 'ショット',
        'Cane' => 'ケイン', 'Rod' => 'ロッド', 'Wand' => 'ウォンド', 'Frame' => 'フレーム', 'Armor' => 'アーマー',
        'Shield' => 'シールド', 'Barrier' => 'バリア',

        // Global UI
        'Server Status' => 'サーバーステータス',
        'Status:' => '状態:',
        'Online' => 'オンライン',
        'Offline' => 'オフライン',
        'Uptime:' => '稼働時間:',
        'Players:' => 'プレイヤー:',
        'Games:' => 'ゲーム:',
        'Rates' => '倍率',
        'EXP:' => '経験値:',
        'Drop:' => 'ドロップ:',
        'Quick Links' => 'クイックリンク',
        'Download Client' => 'クライアントダウンロード',
        'View Full Stats' => '詳細な統計',
        'Discord Community' => 'Discord コミュニティ',
        'Play Now' => '今すぐプレイ',
        'Join Discord' => 'Discord に参加',
        'Join the adventure in the ultimate private Phantasy Star Online BlueBurst server experience.' => '究極のファンタシースターオンラインブルーバーストのプライベートサーバーで冒険に参加しよう。',
        'System Update' => 'システムアップデート',
        'Active Event' => 'アクティブイベント',
        'Coming Soon' => '近日公開',
        'Deep Scan Titan 130: Triple EXP' => 'ディープスキャン・タイタン130: 経験値3倍',
        'Mission Window:' => 'ミッション期間:',
        'The military has declassified restricted combat maneuvers for all Hunters. All enemies defeated this weekend will grant **3x Experience Points**!' => '軍部は全ハンターの制限戦闘機動を解除した。今週末に倒した全ての敵から **経験値3倍** を獲得！',
        'Global Start Times:' => 'グローバル開始時間:',
        'Good luck down there, Hunters! Stay safe on the surface.' => 'ハンター諸君、地下での健闘を祈る！地表での安全を確保せよ。',
        'Discord Integration & Mission Control Live!' => 'Discord連携＆Mission Control 稼働中！',
        "We've officially launched our Discord account linking! You can now securely tie your Discord profile directly to your in-game Hunter characters. Plus, interact with <strong>Mission Control</strong>—our new intelligent Discord chat companion! It recognizes your linked characters, monitors custom server status alerts, and assists with real-time guides right from the chat!" => "Discordアカウントの連携が正式に開始されました！Discordプロフィールをゲーム内のハンターキャラクターと安全に結びつけることができます。さらに、新しいインテリジェントなDiscordチャットコンパニオンである <strong>Mission Control</strong> と交流しましょう！リンクされたキャラクターを認識し、カスタムサーバーステータスアラートを監視し、チャットから直接リアルタイムのガイドを提供します！",
        'New Client Beta Released!' => '新クライアントベータ版リリース！',
        'We\'ve updated our client to version <strong>1.25.13b</strong> (851MB). This new beta client supports both JP and EN players! Download it now from our <a href="downloads.php">downloads page</a>.' => 'クライアントをバージョン <strong>1.25.13b</strong> (851MB) に更新しました。この新しいベータクライアントはJPとEN両方のプレイヤーをサポートします！<a href="downloads.php">ダウンロードページ</a> から今すぐダウンロードしてください。',
        'Please Uninstall your existing client before installing this new release.' => 'この新しいリリースをインストールする前に、既存のクライアントをアンインストールしてください。',
        'Server Updates' => 'サーバーアップデート',
        'We are currently working on the final touches for the website and server. Please check back soon for more updates!' => '現在、ウェブサイトとサーバーの最終調整を行っています。最新情報については、しばらくしてからもう一度ご確認ください！',

        // about.php
        'About Our Server' => '当サーバーについて',
        'Experience Phantasy Star Online Blue Burst like never before on our private server powered by newserv.' => 'newservを搭載したプライベートサーバーで、これまでにないファンタシースターオンラインブルーバーストを体験してください。',
        'Features' => '特徴',
        'Episodes 1-4 Complete:' => 'エピソード1-4 完全収録:',
        'Full native quest lines spanning the entirety of the Phantasy Star Online Blue Burst saga with balanced 1x progression rates.' => 'バランスの取れた1倍の進行率で、ファンタシースターオンラインブルーバーストの全サーガにまたがる完全なネイティブクエストライン。',
        'Cross-Platform Delivery:' => 'クロスプラットフォーム対応:',
        'Seamless client support via native Windows, macOS ports, and Linux / Steam Deck installations.' => 'ネイティブWindows、macOSポート、Linux / Steam Deckへのインストールを通じたシームレスなクライアントサポート。',
        'Hunter\'s Guild Bounty Board:' => 'ハンターズギルド バウンティボード:',
        'Take on unique, personalized bounties offering exclusive gear and material rewards. Track your boss kills and exploration objectives directly on the web, and claim your loot instantly to your character in-game.' => '限定の装備やマテリアル報酬を提供する、ユニークでパーソナライズされたバウンティに挑戦しましょう。ウェブ上で直接ボスの討伐や探索目標を追跡し、ゲーム内のキャラクターに即座に戦利品を請求できます。',
        'Discord Mission Control:' => 'Discord Mission Control:',
        'An advanced interactive chat companion inside our Discord server! Securely link your Discord account to your Hunter profile to allow Mission Control to uniquely interact with your characters, provide real-time server status alerts, and answer questions about PSO lore, item drops, and guides securely in chat.' => '当Discordサーバー内の高度なインタラクティブチャットコンパニオン！Discordアカウントとハンタープロフィールを安全にリンクし、Mission Controlがキャラクターと独自に対話できるようにします。リアルタイムのサーバーステータスアラートを提供し、チャット内で安全にPSOの伝承、アイテムドロップ、ガイドに関する質問に答えます。',
        'Daily Login Streaks:' => '連続ログインボーナス:',
        'Log into the Player Dashboard daily to accumulate bonus rewards to enhance your gameplay.' => 'プレイヤーダッシュボードに毎日ログインして、ゲームプレイを強化するためのボーナス報酬を蓄積しましょう。',
        'Team Check-In Dashboard:' => 'チームチェックインダッシュボード:',
        'View your Guild\'s master roster, unspent team points, and next milestone unlocks from any device.' => 'どのデバイスからでも、ギルドのマスター名簿、未使用のチームポイント、次のマイルストーンのロック解除状況を表示できます。',
        'Wall of Legends Leaderboard:' => 'レジェンドの壁 リーダーボード:',
        'A public hall of fame celebrating the top hunters who successfully complete our most challenging bounties.' => '最も困難なバウンティを成功裏に完了したトップハンターを称える、公開の殿堂。',
        'Modern Engine Stability:' => 'モダンエンジンの安定性:',
        'Clean anti-cheat protocols and blazing fast infrastructure to ensure pristine, uninterrupted play.' => 'クリーンなアンチチートプロトコルと驚異的に高速なインフラストラクチャにより、手付かずの途切れないプレイを保証します。',
        'Server Tech' => 'サーバーテクノロジー',
        'Powered by' => 'Powered by',
        '- an open-source PSO BB server emulator.' => '- オープンソースのPSO BBサーバーエミュレーター。',
        'Stats pulled automatically from server state (players, games, uptime).' => 'サーバーステータス（プレイヤー、ゲーム、稼働時間）から自動的に取得される統計。',
        'Join Our Discord' => 'Discordに参加する',

        // rewards.php
        'Rewards Guide' => '報酬ガイド',
        'Rewards & Bounties Guide' => '報酬＆バウンティガイド',
        'How to use site rewards and guild bounties. Most of this is claimed in the browser, so log into the website when you play if you want to grab things easily.' => 'サイトの報酬とギルドバウンティの使い方です。受け取りの多くはブラウザ側なので、プレイ中にウェブへログインしておくと楽です。',
        'Level Unlocks (dashboard)' => 'Level Unlocks（ダッシュボード）',
        'Log in at <a href="https://psobb.io/">PSOBB.io</a> → <a href="login.php">dashboard</a> → <strong>Level Unlocks</strong>. There you\'ll find: login streak claims, one free daily random item, and rewards every 5 levels.' => '<a href="https://psobb.io/">PSOBB.io</a> にログイン → <a href="login.php">ダッシュボード</a> → <strong>Level Unlocks</strong>。ログインストリーク、毎日1回無料のランダムアイテム、5レベルごとの報酬があります。',
        'Login streak' => 'ログインストリーク',
        'Log in to the game or the website each day to earn rewards. Claim your reward from the streak panel. Rewards include grinders and stat materials.' => '毎日ゲームまたはウェブサイトにログインして報酬を貯めます。ストリークパネルから報酬を受け取ってください。報酬にはグラインダーや能力マテリアルが含まれます。',
        'Daily random item' => '毎日のランダムアイテム',
        'Claim one random item a day just for playing.' => 'プレイしてるだけで、1日1回ランダムアイテムを受け取れます。',
        'Every 5 levels' => '5レベルごと',
        'At 5, 10, 15, etc. you can claim on Level Unlocks. Choose weapon, armor, shield, mag, or a mixed bundle. The drop matches your level and class; armor usually has 4 slots and bonus stats. Each milestone is once per character.' => '5・10・15…で Level Unlocks から受け取り。武器、アーマー、シールド、マグ、またはミックス束から選択。レベルとクラスに合うドロップで、アーマーはだいたい4スロットとボーナス付き。各マイルストーンはキャラごとに1回だけ。',
        'See <a href="missions.php">Bounty Board</a> for your current guild bounty, what to do, and the reward. Complete it in-game, then claim on that page.' => '<a href="missions.php">バウンティボード</a>で、今のギルドバウンティ・やること・報酬を確認。ゲーム内で達成したらそのページで受け取り。',
        'New bounties' => '新しいバウンティ',
        'You only have one personal bounty at a time. After you finish or abandon it, another can show up later while you\'re online—guild mail tells you when there\'s a new one. You won\'t get one every session; check the board when you\'re done playing.' => '個人バウンティは同時に1件だけ。完了か破棄のあと、オンライン中にまた付くことがある。新着はギルド便。毎回付くわけではないので、終わったらボードを見る程度でOK。',
        'Goals and rewards' => '目標と報酬',
        'Goals can be things like meseta, levels, bosses, visiting areas, holding items, techs, using materials, battle wins, challenge stages, playtime, and similar. Rewards are usually gear, mats, meseta, or other items appropriate for your level.' => '目標の例: メセタ、レベル、ボス、エリア、特定アイテム、テク、素材消費、バトル勝利、チャレ、プレイ時間など。報酬はだいたい装備・マテ・メセタ・その他、レベルに合ったもの。',
        'Leaderboard and events' => 'ランキングとイベント',
        'Same page lists top hunters by bounty completions and active community goals. Use abandon on the board if you don\'t want your current bounty.' => '同じページにバウンティ完了数ランキングと進行中のコミュニティ目標。今のバウンティが嫌ならボードで破棄。',
        'Open dashboard' => 'ダッシュボードを開く',
        'Claiming rewards' => '報酬の受け取り',
        'You must be logged into the game with a character and in an active lobby—either on Pioneer 2 or on a map—when you claim rewards. The ship lobby will not work. Applies to streak rewards, daily items, level rewards, and bounty claims.' => '報酬を受け取るときは、ゲームにキャラクターでログインし、アクティブなロビーにいる必要があります—パイオニア2またはマップ上どちらでも可。船舶ロビーでは受けられません。ストリーク、デイリー、レベル報酬、バウンティの受け取りに適用されます。',
        'Reading missions or the leaderboard on your phone is fine. When you claim, the same requirement applies—logged into the game with a character, active lobby on Pioneer 2 or a map, not the ship lobby.' => 'スマホでミッションやランキングを読むのは問題ありません。受け取るときも同様に、ゲームにキャラでログインし、パイオニア2またはマップ上のアクティブロビーにいる必要があり、船舶ロビーではだめです。',
        'Open Bounty Board' => 'バウンティボードを開く',

        // downloads.php
        'Download Clients' => 'クライアントのダウンロード',
        'Download the patched PSO Blue Burst client for your platform. Follow the instructions after download.' => 'お使いのプラットフォームにパッチ適用済みのPSO Blue Burstクライアントをダウンロードしてください。ダウンロード後は手順に従ってください。',
        'Windows (Beta)' => 'Windows（ベータ版）',
        'Native PSO BB PC client with Widescreen support and Frame generation. <strong>Supports both JP and EN players.</strong>' => 'ワイドスクリーン対応とフレーム生成を備えたネイティブPSO BB PCクライアント。<strong>JPプレイヤーとENプレイヤーの両方をサポートします。</strong>',
        'Download' => 'ダウンロード',
        'Requires Windows 10 or later' => 'Windows 10以降が必要です',
        'Based on the amazing work by' => '素晴らしい取り組みに基づいています：',
        'Mac (Alpha)' => 'Mac（アルファ版）',
        'PSO BB Mac client.' => 'PSO BB Macクライアント。',
        'Requires Macbook Pro or Macbook Air M2 or higher' => 'Macbook ProまたはMacbook Air M2以上が必要です',
        'Linux & Steam Deck' => 'Linux ＆ Steam Deck',
        'Native support via Wine/Proton.' => 'Wine/Protonによるネイティブサポート。',
        'Steam Deck (Desktop Mode):' => 'Steam Deck (デスクトップモード):',
        '(Click command to copy)' => '(コマンドをクリックしてコピー)',
        'Other Linux:' => 'その他のLinux:',
        'Download Zip' => 'Zipをダウンロード',
        'Ubuntu 20.04+ or SteamOS' => 'Ubuntu 20.04+ または SteamOS',
        'Installation Instructions' => 'インストール手順',
        'Download the client for your platform.' => 'お使いのプラットフォームのクライアントをダウンロードしてください。',
        'While waiting for the download, <a href="/register.php">create account</a> via website login.' => 'ダウンロードを待っている間に、ウェブサイトのログインから<a href="/register.php">アカウントを作成</a>してください。',
        'Run the installer.' => 'インストーラーを実行します。',
        'Launch PSOBB and select options, customize to your preferences.' => 'PSOBBを起動し、オプションを選択して、好みに合わせてカスタマイズします。',
        'Exempt psobb.exe from your antivirus.' => 'アンチウイルスソフトウェアの除外リストにpsobb.exeを追加してください。',
        'Launch the game when you are ready!' => '準備ができたらゲームを起動してください！',
        'Happy hunting on Ragol!' => 'ラグオルでの狩猟をお楽しみください！',
        '<strong>Note:</strong> Patches from newserv/system/patch-pc applied. Server address: <code>psobb.io</code>' => '<strong>注意:</strong> newserv/system/patch-pcのパッチが適用されています。サーバーアドレス: <code>psobb.io</code>',

        // Common Item Names (For Daily Rewards)
        '1000 Meseta' => '1000 メセタ',
        'Star Atomizer' => 'スターアトマイザー',
        'Moon Atomizer' => 'ムーンアトマイザー',
        'Trimate' => 'トリメイト',
        'Trifluid' => 'トリフルイド',
        'Sol Atomizer' => 'ソルアトマイザー',
        'Telepipe' => 'テレパイプ',
        'Scape Doll' => 'スケープドール',
        'Photon Drop x2' => 'フォトンドロップ x2',
        'Antidote' => 'アンティドート',
        'Antiparalysis' => 'アンティパラライズ',

        // unlocks.php
        'Player Dashboard' => 'プレイヤーダッシュボード',
        'Live Server Stats' => 'ライブサーバ統計',
        'Total Players:' => '総プレイヤー数:',
        'Active Games:' => 'アクティブゲーム:',
        'Server Name:' => 'サーバー名:',
        'Online Players' => 'オンラインプレイヤー',
        'Name' => '名前',
        'Level' => 'レベル',
        'Class' => 'クラス',
        'Section ID' => 'セクションID',
        'Rare Drop Table' => 'レアドロップ表',
        'Enter a search parameter to populate the table.' => '検索条件を入力するとテーブルが表示されます。',
        'Rare probabilities are calculated against other rare items that share the same drop source, not on drop chance as a whole.' => 'レアの確率は、ドロップ全体に対する率ではなく、同じドロップ元（ソース）を共有する他のレアアイテム同士での相対的比較として計算されます。',
        'Loading players...' => 'プレイヤーを読み込み中...',
        'Active Games' => 'アクティブなゲーム',
        'Game Name' => 'ゲーム名',
        'Mode' => 'モード',
        'Episode' => 'エピソード',
        'Difficulty' => '難易度',
        'Loading games...' => 'ゲームを読み込み中...',
        'Quick Stats' => 'クイック統計',
        'EXP Rate:' => 'EXP倍率:',
        'Drop Rate:' => 'ドロップ倍率:',
        'Wall of Legends' => 'レジェンドの壁',
        'Back to Home' => 'ホームに戻る',

        // login.php & dashboard
        'Hunter\'s License Login' => 'ハンターズライセンス ログイン',
        'Access your account data, character stats, and bank.' => 'アカウントデータ、キャラクターステータス、およびバンクにアクセスします。',
        'Username' => 'ユーザー名',
        'Enter your username' => 'ユーザー名を入力',
        'Password' => 'パスワード',
        'Enter your password' => 'パスワードを入力',
        'Security Check' => 'セキュリティチェック',
        'Enter code' => 'コードを入力',
        'Login' => 'ログイン',
        'Forgot Password?' => 'パスワードをお忘れですか？',
        'Don\'t have an account?' => 'アカウントをお持ちではありませんか？',
        'Create one here' => 'ここで作成',
        'Welcome,' => 'ようこそ、',
        'Logout' => 'ログアウト',
        'HUNTER\'S LICENSE' => 'ハンターズライセンス',
        'NAME' => '名前',
        'GUILD CARD ID' => 'ギルドカードID',
        'TEAM' => 'チーム',
        'STATUS: ACTIVE' => 'ステータス: アクティブ',
        '🎁 Claim Level Rewards' => '🎁 レベル報酬を受け取る',
        '🎯 Hunter\'s Guild Bounty Board' => '🎯 ハンターズギルド バウンティボード',
        'Open Admin Panel' => '管理パネルを開く',
        'Integrations' => '連携',
        'Sign in with Discord' => 'Discordでサインイン',
        'Discord Linked' => 'Discord連携済み',
        'Unlink' => '連携解除',
        'Actions' => 'アクション',
        'Change Password' => 'パスワードを変更',
        'Danger Zone' => '危険ゾーン',
        'Delete Account' => 'アカウントを削除',
        'Current Password' => '現在のパスワード',
        'New Password' => '新しいパスワード',
        'Confirm New Password' => '新しいパスワードを確認',
        'Cancel' => 'キャンセル',
        'Update' => '更新',
        'Are you sure you want to delete your account? This action cannot be undone.' => '本当にアカウントを削除しますか？この操作は元に戻せません。',
        'Please enter your password to confirm:' => '確認のためパスワードを入力してください:',
        'Confirm Delete' => '削除を確認',

        // register.php
        'Create Account' => 'アカウントを作成',
        'Register for Phantasy Star Online Blue Burst.' => 'ファンタシースターオンラインブルーバーストに登録します。',
        'Email Address' => 'メールアドレス',
        'Confirm Password' => 'パスワードを確認',
        'Sign Up' => 'サインアップ',
        'Already have an account?' => 'すでにアカウントをお持ちですか？',
        'Login here' => 'ここでログイン',
        'Passwords do not match.' => 'パスワードが一致しません。',
        'Username and password cannot contain spaces.' => 'ユーザー名とパスワードにスペースを含めることはできません。',
        'Creating Account...' => 'アカウントを作成中...',
        'Connection error. Please try again.' => '接続エラー。もう一度やり直してください。',

        // missions.php
        'Hunters Guild Active Roster' => 'ハンターズギルド アクティブロースター',
        'The official Pioneer 2 Bounty Board. Complete unique, specially curated quests to earn meseta, rare items, and global recognition.' => '公式のパイオニア2バウンティボード。特別に厳選されたユニークなクエストを完了して、メセタ、レアアイテム、そしてグローバルな名声を手に入れましょう。',
        '🎁 Ready to Redeem' => '🎁 交換可能',
        'Mission Complete!' => 'ミッション完了！',
        'Awaiting Claim' => '受け取り待ち',
        'Reward' => '報酬',
        'Claim Reward' => '報酬を受け取る',
        'Server Event Completed!' => 'サーバーイベント完了！',
        'Your Contribution' => 'あなたの貢献',
        'points' => 'ポイント',
        'Claim Community Reward' => 'コミュニティ報酬を受け取る',
        'Preparing...' => '準備中...',
        'DROPPING!' => 'ドロップ！',
        'BOUNTY CLAIMED!' => 'バウンティを受け取りました！',
        'Claimed!' => '受け取り済み！',
        'REWARD CLAIMED!' => '報酬を受け取りました！',
        'Connection error: ' => '接続エラー: ',
        'Are you sure you want to abandon this quest? It will be removed from your active bounties completely.' => '本当にこのクエストを破棄しますか？アクティブなバウンティから完全に削除されます。',
        'Abandoning...' => '破棄中...',
        'Abandoned' => '破棄済み',
        'Failed to abandon quest.' => 'クエストの破棄に失敗しました。',
        'Abandon Quest' => 'クエストを破棄',
        'Active Server Events' => 'アクティブなサーバーイベント',
        'Community Event' => 'コミュニティイベント',
        'Directive' => '指令',
        'Community Reward' => 'コミュニティ報酬',
        'Active Personal Bounties' => 'アクティブな個人バウンティ',
        'No active bounties at the moment. Check back soon!' => '現在アクティブなバウンティはありません。また後で確認してください！',
        'Hunter: ' => 'ハンター: ',
        'Active' => 'アクティブ',
        'Top Hunters' => 'トップハンター',
        'The leaderboard is waiting for its first legend.' => 'リーダーボードは最初の伝説を待っています。',
        'How to Play' => '遊び方',
        'The Game Master automatically generates specially curated bounties tailored specifically to your character\'s stats and classes.' => 'ゲームマスターは、あなたのキャラクターのステータスやクラスに合わせた特別に厳選されたバウンティを自動的に生成します。',
        'From time to time, special server-wide bounties appear alongside personal hunts.' => '個人の依頼に加えて、期間限定のサーバー全体バウンティが表示されることがあります。',

        // forgot_password.php & reset_password.php
        'Recover Account' => 'アカウントを復元',
        'Enter the email address associated with your account. We will send you a link to reset your password.' => 'アカウントに関連付けられているメールアドレスを入力してください。パスワードをリセットするためのリンクを送信します。',
        'Send Reset Link' => 'リセットリンクを送信',
        'Back to Login' => 'ログインに戻る',
        'Sending...' => '送信中...',
        'Failed to send email.' => 'メールの送信に失敗しました。',
        'Set New Password' => '新しいパスワードを設定',
        'Invalid request. No token provided.' => '無効なリクエスト。トークンが提供されていません。',
        'Reset Password' => 'パスワードをリセット',
        'Processing...' => '処理中...',
        'Password updated successfully!' => 'パスワードが正常に更新されました！',
        'Reset failed.' => 'リセットに失敗しました。'
    ]
];

function __($key, ...$args) {
    global $PSO_LANG, $I18N;
    
    $translated = $key;
    if ($PSO_LANG === 'jp' && isset($I18N['jp'][$key])) {
        $translated = $I18N['jp'][$key];
    }
    
    if (!empty($args)) {
        return sprintf($translated, ...$args);
    }
    return $translated;
}
?>
